//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using static Unity.Mathematics.math;
using Burst.Compiler.IL.Tests;

namespace Unity.Mathematics.Tests
{
    [TestFixture]
    public class TestBool4
    {
        [TestCompiler]
        public static void bool4_constructor()
        {
            bool4 a = new bool4(false, true, false, true);
            TestUtils.AreEqual(false, a.x);
            TestUtils.AreEqual(true, a.y);
            TestUtils.AreEqual(false, a.z);
            TestUtils.AreEqual(true, a.w);
        }

        [TestCompiler]
        public static void bool4_scalar_constructor()
        {
            bool4 a = new bool4(true);
            TestUtils.AreEqual(true, a.x);
            TestUtils.AreEqual(true, a.y);
            TestUtils.AreEqual(true, a.z);
            TestUtils.AreEqual(true, a.w);
        }

        [TestCompiler]
        public static void bool4_static_constructor()
        {
            bool4 a = bool4(false, true, false, true);
            TestUtils.AreEqual(false, a.x);
            TestUtils.AreEqual(true, a.y);
            TestUtils.AreEqual(false, a.z);
            TestUtils.AreEqual(true, a.w);
        }

        [TestCompiler]
        public static void bool4_static_scalar_constructor()
        {
            bool4 a = bool4(true);
            TestUtils.AreEqual(true, a.x);
            TestUtils.AreEqual(true, a.y);
            TestUtils.AreEqual(true, a.z);
            TestUtils.AreEqual(true, a.w);
        }

        [TestCompiler]
        public static void bool4_operator_equal_wide_wide()
        {
            bool4 a0 = bool4(true, false, true, false);
            bool4 b0 = bool4(true, false, false, false);
            bool4 r0 = bool4(true, true, false, true);
            TestUtils.AreEqual(r0, a0 == b0);

            bool4 a1 = bool4(false, true, false, false);
            bool4 b1 = bool4(true, false, false, true);
            bool4 r1 = bool4(false, false, true, false);
            TestUtils.AreEqual(r1, a1 == b1);

            bool4 a2 = bool4(true, false, true, false);
            bool4 b2 = bool4(false, false, false, false);
            bool4 r2 = bool4(false, true, false, true);
            TestUtils.AreEqual(r2, a2 == b2);

            bool4 a3 = bool4(true, true, false, true);
            bool4 b3 = bool4(true, false, false, false);
            bool4 r3 = bool4(true, false, true, false);
            TestUtils.AreEqual(r3, a3 == b3);
        }

        [TestCompiler]
        public static void bool4_operator_equal_wide_scalar()
        {
            bool4 a0 = bool4(false, true, false, false);
            bool b0 = (true);
            bool4 r0 = bool4(false, true, false, false);
            TestUtils.AreEqual(r0, a0 == b0);

            bool4 a1 = bool4(false, true, false, false);
            bool b1 = (false);
            bool4 r1 = bool4(true, false, true, true);
            TestUtils.AreEqual(r1, a1 == b1);

            bool4 a2 = bool4(false, true, false, true);
            bool b2 = (true);
            bool4 r2 = bool4(false, true, false, true);
            TestUtils.AreEqual(r2, a2 == b2);

            bool4 a3 = bool4(false, false, false, false);
            bool b3 = (true);
            bool4 r3 = bool4(false, false, false, false);
            TestUtils.AreEqual(r3, a3 == b3);
        }

        [TestCompiler]
        public static void bool4_operator_equal_scalar_wide()
        {
            bool a0 = (false);
            bool4 b0 = bool4(true, false, true, false);
            bool4 r0 = bool4(false, true, false, true);
            TestUtils.AreEqual(r0, a0 == b0);

            bool a1 = (false);
            bool4 b1 = bool4(true, false, false, true);
            bool4 r1 = bool4(false, true, true, false);
            TestUtils.AreEqual(r1, a1 == b1);

            bool a2 = (false);
            bool4 b2 = bool4(true, true, false, true);
            bool4 r2 = bool4(false, false, true, false);
            TestUtils.AreEqual(r2, a2 == b2);

            bool a3 = (false);
            bool4 b3 = bool4(true, true, true, false);
            bool4 r3 = bool4(false, false, false, true);
            TestUtils.AreEqual(r3, a3 == b3);
        }

        [TestCompiler]
        public static void bool4_operator_not_equal_wide_wide()
        {
            bool4 a0 = bool4(true, true, true, false);
            bool4 b0 = bool4(true, false, false, false);
            bool4 r0 = bool4(false, true, true, false);
            TestUtils.AreEqual(r0, a0 != b0);

            bool4 a1 = bool4(false, true, false, false);
            bool4 b1 = bool4(true, false, false, false);
            bool4 r1 = bool4(true, true, false, false);
            TestUtils.AreEqual(r1, a1 != b1);

            bool4 a2 = bool4(false, false, true, true);
            bool4 b2 = bool4(false, true, true, true);
            bool4 r2 = bool4(false, true, false, false);
            TestUtils.AreEqual(r2, a2 != b2);

            bool4 a3 = bool4(true, true, true, true);
            bool4 b3 = bool4(false, false, true, true);
            bool4 r3 = bool4(true, true, false, false);
            TestUtils.AreEqual(r3, a3 != b3);
        }

        [TestCompiler]
        public static void bool4_operator_not_equal_wide_scalar()
        {
            bool4 a0 = bool4(false, true, false, true);
            bool b0 = (false);
            bool4 r0 = bool4(false, true, false, true);
            TestUtils.AreEqual(r0, a0 != b0);

            bool4 a1 = bool4(true, false, false, false);
            bool b1 = (false);
            bool4 r1 = bool4(true, false, false, false);
            TestUtils.AreEqual(r1, a1 != b1);

            bool4 a2 = bool4(false, false, false, true);
            bool b2 = (false);
            bool4 r2 = bool4(false, false, false, true);
            TestUtils.AreEqual(r2, a2 != b2);

            bool4 a3 = bool4(false, false, false, true);
            bool b3 = (false);
            bool4 r3 = bool4(false, false, false, true);
            TestUtils.AreEqual(r3, a3 != b3);
        }

        [TestCompiler]
        public static void bool4_operator_not_equal_scalar_wide()
        {
            bool a0 = (true);
            bool4 b0 = bool4(false, false, true, false);
            bool4 r0 = bool4(true, true, false, true);
            TestUtils.AreEqual(r0, a0 != b0);

            bool a1 = (false);
            bool4 b1 = bool4(false, true, true, true);
            bool4 r1 = bool4(false, true, true, true);
            TestUtils.AreEqual(r1, a1 != b1);

            bool a2 = (false);
            bool4 b2 = bool4(false, false, false, false);
            bool4 r2 = bool4(false, false, false, false);
            TestUtils.AreEqual(r2, a2 != b2);

            bool a3 = (true);
            bool4 b3 = bool4(false, false, true, false);
            bool4 r3 = bool4(true, true, false, true);
            TestUtils.AreEqual(r3, a3 != b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_and_wide_wide()
        {
            bool4 a0 = bool4(false, false, true, true);
            bool4 b0 = bool4(false, false, true, false);
            bool4 r0 = bool4(false, false, true, false);
            TestUtils.AreEqual(r0, a0 & b0);

            bool4 a1 = bool4(false, false, true, true);
            bool4 b1 = bool4(true, true, false, false);
            bool4 r1 = bool4(false, false, false, false);
            TestUtils.AreEqual(r1, a1 & b1);

            bool4 a2 = bool4(true, false, true, true);
            bool4 b2 = bool4(true, true, false, false);
            bool4 r2 = bool4(true, false, false, false);
            TestUtils.AreEqual(r2, a2 & b2);

            bool4 a3 = bool4(true, true, false, false);
            bool4 b3 = bool4(false, false, true, false);
            bool4 r3 = bool4(false, false, false, false);
            TestUtils.AreEqual(r3, a3 & b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_and_wide_scalar()
        {
            bool4 a0 = bool4(true, false, false, true);
            bool b0 = (true);
            bool4 r0 = bool4(true, false, false, true);
            TestUtils.AreEqual(r0, a0 & b0);

            bool4 a1 = bool4(true, false, false, false);
            bool b1 = (false);
            bool4 r1 = bool4(false, false, false, false);
            TestUtils.AreEqual(r1, a1 & b1);

            bool4 a2 = bool4(false, true, true, false);
            bool b2 = (true);
            bool4 r2 = bool4(false, true, true, false);
            TestUtils.AreEqual(r2, a2 & b2);

            bool4 a3 = bool4(false, true, true, false);
            bool b3 = (true);
            bool4 r3 = bool4(false, true, true, false);
            TestUtils.AreEqual(r3, a3 & b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_and_scalar_wide()
        {
            bool a0 = (false);
            bool4 b0 = bool4(false, false, true, true);
            bool4 r0 = bool4(false, false, false, false);
            TestUtils.AreEqual(r0, a0 & b0);

            bool a1 = (true);
            bool4 b1 = bool4(false, true, false, false);
            bool4 r1 = bool4(false, true, false, false);
            TestUtils.AreEqual(r1, a1 & b1);

            bool a2 = (false);
            bool4 b2 = bool4(true, false, false, false);
            bool4 r2 = bool4(false, false, false, false);
            TestUtils.AreEqual(r2, a2 & b2);

            bool a3 = (true);
            bool4 b3 = bool4(true, true, true, false);
            bool4 r3 = bool4(true, true, true, false);
            TestUtils.AreEqual(r3, a3 & b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_or_wide_wide()
        {
            bool4 a0 = bool4(true, true, true, false);
            bool4 b0 = bool4(false, false, false, false);
            bool4 r0 = bool4(true, true, true, false);
            TestUtils.AreEqual(r0, a0 | b0);

            bool4 a1 = bool4(true, false, true, true);
            bool4 b1 = bool4(true, true, true, false);
            bool4 r1 = bool4(true, true, true, true);
            TestUtils.AreEqual(r1, a1 | b1);

            bool4 a2 = bool4(false, true, true, true);
            bool4 b2 = bool4(false, true, false, false);
            bool4 r2 = bool4(false, true, true, true);
            TestUtils.AreEqual(r2, a2 | b2);

            bool4 a3 = bool4(true, true, true, false);
            bool4 b3 = bool4(true, true, true, true);
            bool4 r3 = bool4(true, true, true, true);
            TestUtils.AreEqual(r3, a3 | b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_or_wide_scalar()
        {
            bool4 a0 = bool4(true, true, false, true);
            bool b0 = (true);
            bool4 r0 = bool4(true, true, true, true);
            TestUtils.AreEqual(r0, a0 | b0);

            bool4 a1 = bool4(true, true, false, true);
            bool b1 = (true);
            bool4 r1 = bool4(true, true, true, true);
            TestUtils.AreEqual(r1, a1 | b1);

            bool4 a2 = bool4(false, true, false, false);
            bool b2 = (false);
            bool4 r2 = bool4(false, true, false, false);
            TestUtils.AreEqual(r2, a2 | b2);

            bool4 a3 = bool4(true, true, true, true);
            bool b3 = (false);
            bool4 r3 = bool4(true, true, true, true);
            TestUtils.AreEqual(r3, a3 | b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_or_scalar_wide()
        {
            bool a0 = (true);
            bool4 b0 = bool4(true, true, false, false);
            bool4 r0 = bool4(true, true, true, true);
            TestUtils.AreEqual(r0, a0 | b0);

            bool a1 = (true);
            bool4 b1 = bool4(true, true, false, false);
            bool4 r1 = bool4(true, true, true, true);
            TestUtils.AreEqual(r1, a1 | b1);

            bool a2 = (true);
            bool4 b2 = bool4(true, false, true, true);
            bool4 r2 = bool4(true, true, true, true);
            TestUtils.AreEqual(r2, a2 | b2);

            bool a3 = (false);
            bool4 b3 = bool4(false, false, false, true);
            bool4 r3 = bool4(false, false, false, true);
            TestUtils.AreEqual(r3, a3 | b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_xor_wide_wide()
        {
            bool4 a0 = bool4(true, false, false, true);
            bool4 b0 = bool4(true, true, false, true);
            bool4 r0 = bool4(false, true, false, false);
            TestUtils.AreEqual(r0, a0 ^ b0);

            bool4 a1 = bool4(false, false, false, true);
            bool4 b1 = bool4(false, true, false, true);
            bool4 r1 = bool4(false, true, false, false);
            TestUtils.AreEqual(r1, a1 ^ b1);

            bool4 a2 = bool4(false, false, true, true);
            bool4 b2 = bool4(false, false, false, true);
            bool4 r2 = bool4(false, false, true, false);
            TestUtils.AreEqual(r2, a2 ^ b2);

            bool4 a3 = bool4(false, false, true, false);
            bool4 b3 = bool4(false, false, true, true);
            bool4 r3 = bool4(false, false, false, true);
            TestUtils.AreEqual(r3, a3 ^ b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_xor_wide_scalar()
        {
            bool4 a0 = bool4(false, false, true, true);
            bool b0 = (false);
            bool4 r0 = bool4(false, false, true, true);
            TestUtils.AreEqual(r0, a0 ^ b0);

            bool4 a1 = bool4(false, false, false, false);
            bool b1 = (false);
            bool4 r1 = bool4(false, false, false, false);
            TestUtils.AreEqual(r1, a1 ^ b1);

            bool4 a2 = bool4(false, true, false, true);
            bool b2 = (false);
            bool4 r2 = bool4(false, true, false, true);
            TestUtils.AreEqual(r2, a2 ^ b2);

            bool4 a3 = bool4(true, true, false, true);
            bool b3 = (true);
            bool4 r3 = bool4(false, false, true, false);
            TestUtils.AreEqual(r3, a3 ^ b3);
        }

        [TestCompiler]
        public static void bool4_operator_bitwise_xor_scalar_wide()
        {
            bool a0 = (true);
            bool4 b0 = bool4(true, false, true, true);
            bool4 r0 = bool4(false, true, false, false);
            TestUtils.AreEqual(r0, a0 ^ b0);

            bool a1 = (false);
            bool4 b1 = bool4(true, true, false, false);
            bool4 r1 = bool4(true, true, false, false);
            TestUtils.AreEqual(r1, a1 ^ b1);

            bool a2 = (true);
            bool4 b2 = bool4(true, false, false, true);
            bool4 r2 = bool4(false, true, true, false);
            TestUtils.AreEqual(r2, a2 ^ b2);

            bool a3 = (false);
            bool4 b3 = bool4(true, true, false, true);
            bool4 r3 = bool4(true, true, false, true);
            TestUtils.AreEqual(r3, a3 ^ b3);
        }

        [TestCompiler]
        public static void bool4_operator_logical_not()
        {
            bool4 a0 = bool4(true, true, false, false);
            bool4 r0 = bool4(false, false, true, true);
            TestUtils.AreEqual(r0, !a0);

            bool4 a1 = bool4(true, true, false, true);
            bool4 r1 = bool4(false, false, true, false);
            TestUtils.AreEqual(r1, !a1);

            bool4 a2 = bool4(false, false, false, true);
            bool4 r2 = bool4(true, true, true, false);
            TestUtils.AreEqual(r2, !a2);

            bool4 a3 = bool4(true, false, true, true);
            bool4 r3 = bool4(false, true, false, false);
            TestUtils.AreEqual(r3, !a3);
        }

        [TestCompiler]
        public static void bool4_swizzle()
        {
            var v = new bool4(false, true, false, true);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xxxx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xxxy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xxxz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xxxw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xxyx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xxyy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xxyz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xxyw);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xxzx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xxzy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xxzz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xxzw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xxwx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xxwy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xxwz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xxww);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xyxx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xyxy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xyxz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xyxw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xyyx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xyyy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xyyz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xyyw);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xyzx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xyzy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xyzz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xyzw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xywx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xywy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xywz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xyww);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xzxx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xzxy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xzxz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xzxw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xzyx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xzyy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xzyz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xzyw);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xzzx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xzzy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.xzzz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.xzzw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xzwx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xzwy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.xzwz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.xzww);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xwxx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xwxy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xwxz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xwxw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xwyx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xwyy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xwyz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xwyw);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xwzx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xwzy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.xwzz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.xwzw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xwwx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xwwy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.xwwz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.xwww);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yxxx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yxxy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yxxz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yxxw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yxyx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yxyy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yxyz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yxyw);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yxzx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yxzy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yxzz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yxzw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yxwx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yxwy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yxwz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yxww);
            TestUtils.AreEqual(bool4(true, true, false, false), v.yyxx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.yyxy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.yyxz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.yyxw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.yyyx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.yyyy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.yyyz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.yyyw);
            TestUtils.AreEqual(bool4(true, true, false, false), v.yyzx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.yyzy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.yyzz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.yyzw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.yywx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.yywy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.yywz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.yyww);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yzxx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yzxy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yzxz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yzxw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yzyx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yzyy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yzyz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yzyw);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yzzx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yzzy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.yzzz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.yzzw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yzwx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yzwy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.yzwz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.yzww);
            TestUtils.AreEqual(bool4(true, true, false, false), v.ywxx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.ywxy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.ywxz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.ywxw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.ywyx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.ywyy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.ywyz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.ywyw);
            TestUtils.AreEqual(bool4(true, true, false, false), v.ywzx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.ywzy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.ywzz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.ywzw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.ywwx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.ywwy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.ywwz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.ywww);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zxxx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zxxy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zxxz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zxxw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zxyx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zxyy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zxyz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zxyw);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zxzx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zxzy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zxzz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zxzw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zxwx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zxwy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zxwz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zxww);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zyxx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zyxy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zyxz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zyxw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zyyx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zyyy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zyyz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zyyw);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zyzx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zyzy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zyzz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zyzw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zywx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zywy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zywz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zyww);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zzxx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zzxy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zzxz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zzxw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zzyx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zzyy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zzyz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zzyw);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zzzx);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zzzy);
            TestUtils.AreEqual(bool4(false, false, false, false), v.zzzz);
            TestUtils.AreEqual(bool4(false, false, false, true), v.zzzw);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zzwx);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zzwy);
            TestUtils.AreEqual(bool4(false, false, true, false), v.zzwz);
            TestUtils.AreEqual(bool4(false, false, true, true), v.zzww);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zwxx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zwxy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zwxz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zwxw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zwyx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zwyy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zwyz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zwyw);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zwzx);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zwzy);
            TestUtils.AreEqual(bool4(false, true, false, false), v.zwzz);
            TestUtils.AreEqual(bool4(false, true, false, true), v.zwzw);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zwwx);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zwwy);
            TestUtils.AreEqual(bool4(false, true, true, false), v.zwwz);
            TestUtils.AreEqual(bool4(false, true, true, true), v.zwww);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wxxx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wxxy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wxxz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wxxw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wxyx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wxyy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wxyz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wxyw);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wxzx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wxzy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wxzz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wxzw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wxwx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wxwy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wxwz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wxww);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wyxx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wyxy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wyxz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wyxw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wyyx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wyyy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wyyz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wyyw);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wyzx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wyzy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wyzz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wyzw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wywx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wywy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wywz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wyww);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wzxx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wzxy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wzxz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wzxw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wzyx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wzyy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wzyz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wzyw);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wzzx);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wzzy);
            TestUtils.AreEqual(bool4(true, false, false, false), v.wzzz);
            TestUtils.AreEqual(bool4(true, false, false, true), v.wzzw);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wzwx);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wzwy);
            TestUtils.AreEqual(bool4(true, false, true, false), v.wzwz);
            TestUtils.AreEqual(bool4(true, false, true, true), v.wzww);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wwxx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wwxy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wwxz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wwxw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wwyx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wwyy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wwyz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wwyw);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wwzx);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wwzy);
            TestUtils.AreEqual(bool4(true, true, false, false), v.wwzz);
            TestUtils.AreEqual(bool4(true, true, false, true), v.wwzw);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wwwx);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wwwy);
            TestUtils.AreEqual(bool4(true, true, true, false), v.wwwz);
            TestUtils.AreEqual(bool4(true, true, true, true), v.wwww);
            TestUtils.AreEqual(bool3(false, false, false), v.xxx);
            TestUtils.AreEqual(bool3(false, false, true), v.xxy);
            TestUtils.AreEqual(bool3(false, false, false), v.xxz);
            TestUtils.AreEqual(bool3(false, false, true), v.xxw);
            TestUtils.AreEqual(bool3(false, true, false), v.xyx);
            TestUtils.AreEqual(bool3(false, true, true), v.xyy);
            TestUtils.AreEqual(bool3(false, true, false), v.xyz);
            TestUtils.AreEqual(bool3(false, true, true), v.xyw);
            TestUtils.AreEqual(bool3(false, false, false), v.xzx);
            TestUtils.AreEqual(bool3(false, false, true), v.xzy);
            TestUtils.AreEqual(bool3(false, false, false), v.xzz);
            TestUtils.AreEqual(bool3(false, false, true), v.xzw);
            TestUtils.AreEqual(bool3(false, true, false), v.xwx);
            TestUtils.AreEqual(bool3(false, true, true), v.xwy);
            TestUtils.AreEqual(bool3(false, true, false), v.xwz);
            TestUtils.AreEqual(bool3(false, true, true), v.xww);
            TestUtils.AreEqual(bool3(true, false, false), v.yxx);
            TestUtils.AreEqual(bool3(true, false, true), v.yxy);
            TestUtils.AreEqual(bool3(true, false, false), v.yxz);
            TestUtils.AreEqual(bool3(true, false, true), v.yxw);
            TestUtils.AreEqual(bool3(true, true, false), v.yyx);
            TestUtils.AreEqual(bool3(true, true, true), v.yyy);
            TestUtils.AreEqual(bool3(true, true, false), v.yyz);
            TestUtils.AreEqual(bool3(true, true, true), v.yyw);
            TestUtils.AreEqual(bool3(true, false, false), v.yzx);
            TestUtils.AreEqual(bool3(true, false, true), v.yzy);
            TestUtils.AreEqual(bool3(true, false, false), v.yzz);
            TestUtils.AreEqual(bool3(true, false, true), v.yzw);
            TestUtils.AreEqual(bool3(true, true, false), v.ywx);
            TestUtils.AreEqual(bool3(true, true, true), v.ywy);
            TestUtils.AreEqual(bool3(true, true, false), v.ywz);
            TestUtils.AreEqual(bool3(true, true, true), v.yww);
            TestUtils.AreEqual(bool3(false, false, false), v.zxx);
            TestUtils.AreEqual(bool3(false, false, true), v.zxy);
            TestUtils.AreEqual(bool3(false, false, false), v.zxz);
            TestUtils.AreEqual(bool3(false, false, true), v.zxw);
            TestUtils.AreEqual(bool3(false, true, false), v.zyx);
            TestUtils.AreEqual(bool3(false, true, true), v.zyy);
            TestUtils.AreEqual(bool3(false, true, false), v.zyz);
            TestUtils.AreEqual(bool3(false, true, true), v.zyw);
            TestUtils.AreEqual(bool3(false, false, false), v.zzx);
            TestUtils.AreEqual(bool3(false, false, true), v.zzy);
            TestUtils.AreEqual(bool3(false, false, false), v.zzz);
            TestUtils.AreEqual(bool3(false, false, true), v.zzw);
            TestUtils.AreEqual(bool3(false, true, false), v.zwx);
            TestUtils.AreEqual(bool3(false, true, true), v.zwy);
            TestUtils.AreEqual(bool3(false, true, false), v.zwz);
            TestUtils.AreEqual(bool3(false, true, true), v.zww);
            TestUtils.AreEqual(bool3(true, false, false), v.wxx);
            TestUtils.AreEqual(bool3(true, false, true), v.wxy);
            TestUtils.AreEqual(bool3(true, false, false), v.wxz);
            TestUtils.AreEqual(bool3(true, false, true), v.wxw);
            TestUtils.AreEqual(bool3(true, true, false), v.wyx);
            TestUtils.AreEqual(bool3(true, true, true), v.wyy);
            TestUtils.AreEqual(bool3(true, true, false), v.wyz);
            TestUtils.AreEqual(bool3(true, true, true), v.wyw);
            TestUtils.AreEqual(bool3(true, false, false), v.wzx);
            TestUtils.AreEqual(bool3(true, false, true), v.wzy);
            TestUtils.AreEqual(bool3(true, false, false), v.wzz);
            TestUtils.AreEqual(bool3(true, false, true), v.wzw);
            TestUtils.AreEqual(bool3(true, true, false), v.wwx);
            TestUtils.AreEqual(bool3(true, true, true), v.wwy);
            TestUtils.AreEqual(bool3(true, true, false), v.wwz);
            TestUtils.AreEqual(bool3(true, true, true), v.www);
            TestUtils.AreEqual(bool2(false, false), v.xx);
            TestUtils.AreEqual(bool2(false, true), v.xy);
            TestUtils.AreEqual(bool2(false, false), v.xz);
            TestUtils.AreEqual(bool2(false, true), v.xw);
            TestUtils.AreEqual(bool2(true, false), v.yx);
            TestUtils.AreEqual(bool2(true, true), v.yy);
            TestUtils.AreEqual(bool2(true, false), v.yz);
            TestUtils.AreEqual(bool2(true, true), v.yw);
            TestUtils.AreEqual(bool2(false, false), v.zx);
            TestUtils.AreEqual(bool2(false, true), v.zy);
            TestUtils.AreEqual(bool2(false, false), v.zz);
            TestUtils.AreEqual(bool2(false, true), v.zw);
            TestUtils.AreEqual(bool2(true, false), v.wx);
            TestUtils.AreEqual(bool2(true, true), v.wy);
            TestUtils.AreEqual(bool2(true, false), v.wz);
            TestUtils.AreEqual(bool2(true, true), v.ww);
        }

        [TestCompiler]
        public static void bool4_colorswizzle()
        {
        }


    }
}
