//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using static Unity.Mathematics.math;
using Burst.Compiler.IL.Tests;

namespace Unity.Mathematics.Tests
{
    [TestFixture]
    public class TestUint3x2
    {
        [TestCompiler]
        public static void uint3x2_zero()
        {
            TestUtils.AreEqual(uint3x2.zero.c0.x, 0u);
            TestUtils.AreEqual(uint3x2.zero.c0.y, 0u);
            TestUtils.AreEqual(uint3x2.zero.c0.z, 0u);
            TestUtils.AreEqual(uint3x2.zero.c1.x, 0u);
            TestUtils.AreEqual(uint3x2.zero.c1.y, 0u);
            TestUtils.AreEqual(uint3x2.zero.c1.z, 0u);
        }

        [TestCompiler]
        public static void uint3x2_operator_equal_wide_wide()
        {
            uint3x2 a0 = uint3x2(1769459654, 197796492, 154243692, 952126595, 689725190, 1225413740);
            uint3x2 b0 = uint3x2(179132783, 1978336870, 1626004111, 424899921, 1894146793, 91777081);
            bool3x2 r0 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint3x2 a1 = uint3x2(459892608, 693366823, 1165697239, 2083074615, 1615698985, 1813156614);
            uint3x2 b1 = uint3x2(256037971, 669679301, 1054971930, 362624852, 1293267305, 143644847);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint3x2 a2 = uint3x2(1222331884, 987584254, 22766760, 2058182171, 1869606666, 707877323);
            uint3x2 b2 = uint3x2(1825864659, 201852545, 776009920, 1868835168, 1191399971, 1352263540);
            bool3x2 r2 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint3x2 a3 = uint3x2(116376311, 1434904089, 1615728304, 2142912288, 656040157, 1481202493);
            uint3x2 b3 = uint3x2(583477616, 738940448, 1849279169, 1159826254, 1737877015, 532610029);
            bool3x2 r3 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_equal_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1759724257, 1997468592, 143140702, 1756461805, 1986782555, 1196177899);
            uint b0 = (1791891760);
            bool3x2 r0 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint3x2 a1 = uint3x2(238163080, 2008027469, 1036427796, 880022489, 339253087, 2017956782);
            uint b1 = (1864507830);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint3x2 a2 = uint3x2(1105164108, 1938793008, 2027323810, 1680430470, 1822281633, 1941465438);
            uint b2 = (15881823);
            bool3x2 r2 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint3x2 a3 = uint3x2(1563160061, 1819421607, 579147650, 1749649185, 1313616237, 1812362468);
            uint b3 = (64651909);
            bool3x2 r3 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_equal_scalar_wide()
        {
            uint a0 = (1977155329);
            uint3x2 b0 = uint3x2(162052257, 1291280073, 522114153, 602804987, 1501793202, 1485975269);
            bool3x2 r0 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint a1 = (182962739);
            uint3x2 b1 = uint3x2(2054056581, 978460589, 1363550636, 1453456227, 131668009, 370871984);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint a2 = (911283419);
            uint3x2 b2 = uint3x2(1300029560, 379685821, 831942423, 1586543452, 64013033, 1356026486);
            bool3x2 r2 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint a3 = (636964527);
            uint3x2 b3 = uint3x2(1956467079, 100162328, 1209878427, 1205509449, 172376936, 1062136542);
            bool3x2 r3 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_not_equal_wide_wide()
        {
            uint3x2 a0 = uint3x2(1114120377, 1328200685, 2055858397, 628379191, 212580972, 2138118298);
            uint3x2 b0 = uint3x2(551411861, 1033798228, 1752427499, 1692279987, 40976337, 724601100);
            bool3x2 r0 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint3x2 a1 = uint3x2(1183215634, 403403153, 132317086, 1609292182, 925970858, 1034076747);
            uint3x2 b1 = uint3x2(1957052399, 1257584257, 1480327454, 488028594, 1406169001, 1968460485);
            bool3x2 r1 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint3x2 a2 = uint3x2(797706087, 1677878785, 1683421549, 1474891802, 611230788, 1922657997);
            uint3x2 b2 = uint3x2(225343558, 2081927683, 686858576, 1819164209, 1943379523, 791131358);
            bool3x2 r2 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint3x2 a3 = uint3x2(515873282, 1616835734, 286372105, 1334077363, 244859168, 1396897395);
            uint3x2 b3 = uint3x2(111738244, 982846016, 137575866, 967731892, 774321591, 104831621);
            bool3x2 r3 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_not_equal_wide_scalar()
        {
            uint3x2 a0 = uint3x2(197085580, 1559123934, 89174026, 874566733, 285035719, 175911184);
            uint b0 = (641022627);
            bool3x2 r0 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint3x2 a1 = uint3x2(2107486277, 1242391870, 812875165, 215397387, 1816051923, 1432332427);
            uint b1 = (882200899);
            bool3x2 r1 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint3x2 a2 = uint3x2(35870207, 695883299, 1755116468, 1841089280, 1254194936, 1231333222);
            uint b2 = (1453358020);
            bool3x2 r2 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint3x2 a3 = uint3x2(13043207, 1882145915, 608371145, 1571504076, 1916573718, 196320053);
            uint b3 = (2131792700);
            bool3x2 r3 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_not_equal_scalar_wide()
        {
            uint a0 = (1823145268);
            uint3x2 b0 = uint3x2(1478442612, 395956316, 1021050384, 506455754, 120739710, 111528848);
            bool3x2 r0 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint a1 = (497993131);
            uint3x2 b1 = uint3x2(1341426941, 981702603, 697361127, 2118726847, 373682311, 718299814);
            bool3x2 r1 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint a2 = (767014928);
            uint3x2 b2 = uint3x2(1004475715, 1402457009, 475620317, 1050918856, 1617498576, 88204597);
            bool3x2 r2 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint a3 = (1171079641);
            uint3x2 b3 = uint3x2(202617696, 1727104700, 1586529029, 1305535353, 464498913, 960870640);
            bool3x2 r3 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_wide_wide()
        {
            uint3x2 a0 = uint3x2(2096784746, 6455590, 1186728125, 2004430503, 903707670, 1290095569);
            uint3x2 b0 = uint3x2(2023955832, 814050279, 2107113757, 1984877677, 229711986, 65531143);
            bool3x2 r0 = bool3x2(false, true, true, false, false, false);
            TestUtils.AreEqual(a0 < b0, r0);

            uint3x2 a1 = uint3x2(33135516, 1136659156, 2103201294, 2092322432, 317443647, 145428344);
            uint3x2 b1 = uint3x2(1739169538, 1442465278, 1706801427, 1236851354, 678269170, 2078986192);
            bool3x2 r1 = bool3x2(true, true, false, false, true, true);
            TestUtils.AreEqual(a1 < b1, r1);

            uint3x2 a2 = uint3x2(421825315, 775702881, 797081946, 486711847, 370856976, 1508350125);
            uint3x2 b2 = uint3x2(248843346, 1119242408, 1391608859, 831566525, 199002555, 501557545);
            bool3x2 r2 = bool3x2(false, true, true, true, false, false);
            TestUtils.AreEqual(a2 < b2, r2);

            uint3x2 a3 = uint3x2(1634507727, 1618343965, 1487640747, 1866663662, 321663320, 680877476);
            uint3x2 b3 = uint3x2(1516195865, 328928308, 1457688009, 527835751, 1730051156, 1878872603);
            bool3x2 r3 = bool3x2(false, false, false, false, true, true);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1111812659, 215280083, 1452878573, 685443717, 1552447661, 1334052403);
            uint b0 = (1393181832);
            bool3x2 r0 = bool3x2(true, true, false, true, false, true);
            TestUtils.AreEqual(a0 < b0, r0);

            uint3x2 a1 = uint3x2(1631047060, 2107896094, 1150022920, 1349894445, 1253959696, 886316879);
            uint b1 = (428772023);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 < b1, r1);

            uint3x2 a2 = uint3x2(996367814, 667435667, 401266960, 1963622811, 250573340, 1986163240);
            uint b2 = (43500883);
            bool3x2 r2 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a2 < b2, r2);

            uint3x2 a3 = uint3x2(1455141496, 845342719, 1054067153, 1304128666, 282268279, 881261520);
            uint b3 = (1807813603);
            bool3x2 r3 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_scalar_wide()
        {
            uint a0 = (1947585822);
            uint3x2 b0 = uint3x2(852724905, 257426229, 1931155895, 891206688, 1637228394, 87657529);
            bool3x2 r0 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a0 < b0, r0);

            uint a1 = (1642732032);
            uint3x2 b1 = uint3x2(716549196, 745331149, 1073136377, 1224927266, 959593884, 1475562958);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 < b1, r1);

            uint a2 = (1850828896);
            uint3x2 b2 = uint3x2(1667723226, 312974729, 768604138, 1734617142, 1788513218, 947431907);
            bool3x2 r2 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a2 < b2, r2);

            uint a3 = (665124971);
            uint3x2 b3 = uint3x2(526266121, 556110438, 1265710125, 584009036, 1107979057, 981386418);
            bool3x2 r3 = bool3x2(false, false, true, false, true, true);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_wide_wide()
        {
            uint3x2 a0 = uint3x2(679407976, 1565104964, 955659700, 1579068177, 2125437566, 437413511);
            uint3x2 b0 = uint3x2(1037249636, 948878199, 1022811823, 1540122195, 639273951, 1840348368);
            bool3x2 r0 = bool3x2(false, true, false, true, true, false);
            TestUtils.AreEqual(a0 > b0, r0);

            uint3x2 a1 = uint3x2(433042806, 86523161, 433920144, 1128363150, 1430252123, 28546361);
            uint3x2 b1 = uint3x2(1458722938, 1025338066, 1780825559, 1442445808, 1055886580, 809782985);
            bool3x2 r1 = bool3x2(false, false, false, false, true, false);
            TestUtils.AreEqual(a1 > b1, r1);

            uint3x2 a2 = uint3x2(1640272676, 1219827111, 729860988, 1646629509, 1480319015, 742519043);
            uint3x2 b2 = uint3x2(627348215, 1100285680, 1355127414, 860855759, 14375850, 757917854);
            bool3x2 r2 = bool3x2(true, true, false, true, true, false);
            TestUtils.AreEqual(a2 > b2, r2);

            uint3x2 a3 = uint3x2(1994504193, 1942450636, 556672053, 1757883729, 114721227, 362921128);
            uint3x2 b3 = uint3x2(1673864053, 1824680438, 1295524124, 1202767129, 1376581777, 447898330);
            bool3x2 r3 = bool3x2(true, true, false, true, false, false);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_wide_scalar()
        {
            uint3x2 a0 = uint3x2(2057056127, 328369940, 977884645, 1927653020, 1805071634, 1951495065);
            uint b0 = (1496952827);
            bool3x2 r0 = bool3x2(true, false, false, true, true, true);
            TestUtils.AreEqual(a0 > b0, r0);

            uint3x2 a1 = uint3x2(187170445, 1984248926, 538865160, 1448725978, 1870289210, 346150889);
            uint b1 = (309800711);
            bool3x2 r1 = bool3x2(false, true, true, true, true, true);
            TestUtils.AreEqual(a1 > b1, r1);

            uint3x2 a2 = uint3x2(819772244, 480802003, 1990373394, 1106501347, 1510847950, 4937056);
            uint b2 = (1418697328);
            bool3x2 r2 = bool3x2(false, false, true, false, true, false);
            TestUtils.AreEqual(a2 > b2, r2);

            uint3x2 a3 = uint3x2(457594840, 2098120134, 733548321, 1706259035, 350112448, 913727938);
            uint b3 = (1341305673);
            bool3x2 r3 = bool3x2(false, true, false, true, false, false);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_scalar_wide()
        {
            uint a0 = (1362109003);
            uint3x2 b0 = uint3x2(142885648, 1660635591, 104009698, 485042379, 1326894883, 1007324999);
            bool3x2 r0 = bool3x2(true, false, true, true, true, true);
            TestUtils.AreEqual(a0 > b0, r0);

            uint a1 = (1835906302);
            uint3x2 b1 = uint3x2(1625555804, 745829307, 1212896249, 438032966, 1953156077, 250146075);
            bool3x2 r1 = bool3x2(true, true, true, true, false, true);
            TestUtils.AreEqual(a1 > b1, r1);

            uint a2 = (279418367);
            uint3x2 b2 = uint3x2(238317957, 414643707, 1261501322, 1930233724, 1709921862, 1109218757);
            bool3x2 r2 = bool3x2(true, false, false, false, false, false);
            TestUtils.AreEqual(a2 > b2, r2);

            uint a3 = (181646471);
            uint3x2 b3 = uint3x2(1504998457, 692255257, 1612264495, 501633267, 668993654, 2033271267);
            bool3x2 r3 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_equal_wide_wide()
        {
            uint3x2 a0 = uint3x2(1772193278, 1575696890, 1129461478, 1160757899, 732614174, 505407897);
            uint3x2 b0 = uint3x2(1170485947, 280845724, 94836958, 710231911, 62412740, 1458247289);
            bool3x2 r0 = bool3x2(false, false, false, false, false, true);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint3x2 a1 = uint3x2(845181177, 1895996546, 1733272281, 1510163679, 1157493614, 2035853300);
            uint3x2 b1 = uint3x2(1910665214, 806067482, 825865086, 382253253, 635819539, 1846095366);
            bool3x2 r1 = bool3x2(true, false, false, false, false, false);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint3x2 a2 = uint3x2(226335126, 1827437131, 1925038167, 102721882, 110219955, 1643730680);
            uint3x2 b2 = uint3x2(1218121558, 2022420424, 538861885, 1996724846, 783861407, 576383233);
            bool3x2 r2 = bool3x2(true, true, false, true, true, false);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint3x2 a3 = uint3x2(1227024208, 1626672632, 328526921, 686582255, 400611759, 1788608407);
            uint3x2 b3 = uint3x2(1495988801, 228067901, 1557519061, 953542180, 1334063563, 1153799594);
            bool3x2 r3 = bool3x2(true, false, true, true, true, false);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_equal_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1331309222, 478791836, 467984397, 684816797, 412606484, 1660050607);
            uint b0 = (692177811);
            bool3x2 r0 = bool3x2(false, true, true, true, true, false);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint3x2 a1 = uint3x2(406933135, 300305325, 795892530, 639098736, 384843721, 831822993);
            uint b1 = (537773128);
            bool3x2 r1 = bool3x2(true, true, false, false, true, false);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint3x2 a2 = uint3x2(669995206, 993917104, 2143139650, 212683631, 587727929, 1449248286);
            uint b2 = (2026234386);
            bool3x2 r2 = bool3x2(true, true, false, true, true, true);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint3x2 a3 = uint3x2(541399087, 1745857413, 1211693585, 1403126997, 1339199616, 75427551);
            uint b3 = (1552946378);
            bool3x2 r3 = bool3x2(true, false, true, true, true, true);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_less_equal_scalar_wide()
        {
            uint a0 = (368122142);
            uint3x2 b0 = uint3x2(1602136857, 1025804484, 572719917, 1670730995, 322281926, 2056320987);
            bool3x2 r0 = bool3x2(true, true, true, true, false, true);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint a1 = (153014038);
            uint3x2 b1 = uint3x2(660460911, 302838143, 771971953, 260376717, 888694354, 1995147646);
            bool3x2 r1 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint a2 = (50363690);
            uint3x2 b2 = uint3x2(248688945, 1910720377, 1839966465, 601850603, 432894977, 747624795);
            bool3x2 r2 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint a3 = (567603209);
            uint3x2 b3 = uint3x2(1025638652, 834791365, 1956749769, 39094770, 186897619, 1130538813);
            bool3x2 r3 = bool3x2(true, true, true, false, false, true);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_equal_wide_wide()
        {
            uint3x2 a0 = uint3x2(1374979366, 545879935, 1322414052, 1123804185, 1251232279, 768853165);
            uint3x2 b0 = uint3x2(215438260, 895664604, 2141461196, 945533420, 1365701491, 1010346143);
            bool3x2 r0 = bool3x2(true, false, false, true, false, false);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint3x2 a1 = uint3x2(582070144, 1263454123, 1500629331, 1851742458, 939335967, 779085610);
            uint3x2 b1 = uint3x2(1515687794, 1130396256, 2054544008, 641613525, 1303489788, 205583136);
            bool3x2 r1 = bool3x2(false, true, false, true, false, true);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint3x2 a2 = uint3x2(944458048, 2046650369, 902952345, 955539678, 1157113010, 257713664);
            uint3x2 b2 = uint3x2(1273778628, 39641088, 1767053835, 1298000488, 410631220, 1506783726);
            bool3x2 r2 = bool3x2(false, true, false, false, true, false);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint3x2 a3 = uint3x2(1319836764, 108383550, 634973154, 604432106, 996865291, 2098409217);
            uint3x2 b3 = uint3x2(1313292743, 1187912061, 564463682, 1578097724, 1390641114, 1420072103);
            bool3x2 r3 = bool3x2(true, false, true, false, false, true);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_equal_wide_scalar()
        {
            uint3x2 a0 = uint3x2(328496099, 1711908264, 1881414926, 520188393, 159789484, 1339033201);
            uint b0 = (781823478);
            bool3x2 r0 = bool3x2(false, true, true, false, false, true);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint3x2 a1 = uint3x2(1235245220, 627782248, 207207443, 1050513019, 115326785, 815764965);
            uint b1 = (598204379);
            bool3x2 r1 = bool3x2(true, true, false, true, false, true);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint3x2 a2 = uint3x2(1663037383, 1877098280, 1438292093, 720338718, 472236552, 1922545138);
            uint b2 = (838304903);
            bool3x2 r2 = bool3x2(true, true, true, false, false, true);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint3x2 a3 = uint3x2(1199061830, 518613082, 1045996504, 649618362, 1209413129, 690261764);
            uint b3 = (1388609205);
            bool3x2 r3 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_greater_equal_scalar_wide()
        {
            uint a0 = (557688741);
            uint3x2 b0 = uint3x2(1371865141, 1033269674, 755002243, 1765845791, 602301797, 2020815501);
            bool3x2 r0 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint a1 = (159421708);
            uint3x2 b1 = uint3x2(1924937716, 394222366, 1704680025, 357243706, 1806378360, 354479574);
            bool3x2 r1 = bool3x2(false, false, false, false, false, false);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint a2 = (1908040605);
            uint3x2 b2 = uint3x2(1835366305, 778033888, 435914601, 1740383551, 295481939, 724118281);
            bool3x2 r2 = bool3x2(true, true, true, true, true, true);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint a3 = (1475647047);
            uint3x2 b3 = uint3x2(498308338, 1143209634, 958641291, 2000731827, 1411497891, 671544291);
            bool3x2 r3 = bool3x2(true, true, true, false, true, true);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_add_wide_wide()
        {
            uint3x2 a0 = uint3x2(225914922, 622990175, 729236185, 1783579909, 1708861806, 380354128);
            uint3x2 b0 = uint3x2(1983696599, 1828130431, 1955603448, 200546650, 731457904, 998973978);
            uint3x2 r0 = uint3x2(2209611521, 2451120606, 2684839633, 1984126559, 2440319710, 1379328106);
            TestUtils.AreEqual(a0 + b0, r0);

            uint3x2 a1 = uint3x2(1029189209, 1403268164, 1141783501, 373364088, 48999294, 2090032850);
            uint3x2 b1 = uint3x2(1620597307, 1031552425, 1402512585, 1734429792, 841221283, 289477406);
            uint3x2 r1 = uint3x2(2649786516, 2434820589, 2544296086, 2107793880, 890220577, 2379510256);
            TestUtils.AreEqual(a1 + b1, r1);

            uint3x2 a2 = uint3x2(772555923, 557651823, 793305044, 1662875947, 660106064, 1225440955);
            uint3x2 b2 = uint3x2(1099919690, 1277992402, 760042536, 101576399, 376929182, 1880916902);
            uint3x2 r2 = uint3x2(1872475613, 1835644225, 1553347580, 1764452346, 1037035246, 3106357857);
            TestUtils.AreEqual(a2 + b2, r2);

            uint3x2 a3 = uint3x2(1931181602, 1833378287, 572899044, 432731205, 1080660284, 162247952);
            uint3x2 b3 = uint3x2(973832289, 1558313950, 269872091, 848751182, 1843435630, 1711283984);
            uint3x2 r3 = uint3x2(2905013891, 3391692237, 842771135, 1281482387, 2924095914, 1873531936);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_add_wide_scalar()
        {
            uint3x2 a0 = uint3x2(395461163, 1754549897, 490977997, 82076982, 111030504, 1375953840);
            uint b0 = (420967776);
            uint3x2 r0 = uint3x2(816428939, 2175517673, 911945773, 503044758, 531998280, 1796921616);
            TestUtils.AreEqual(a0 + b0, r0);

            uint3x2 a1 = uint3x2(372298610, 259325464, 1709985405, 1057574070, 1012884785, 1168371570);
            uint b1 = (1386457204);
            uint3x2 r1 = uint3x2(1758755814, 1645782668, 3096442609, 2444031274, 2399341989, 2554828774);
            TestUtils.AreEqual(a1 + b1, r1);

            uint3x2 a2 = uint3x2(1287234389, 1659776711, 673086186, 1322018946, 1096944220, 992891902);
            uint b2 = (213037110);
            uint3x2 r2 = uint3x2(1500271499, 1872813821, 886123296, 1535056056, 1309981330, 1205929012);
            TestUtils.AreEqual(a2 + b2, r2);

            uint3x2 a3 = uint3x2(1935451029, 616134421, 289220457, 352074636, 301617568, 1270879501);
            uint b3 = (1043851553);
            uint3x2 r3 = uint3x2(2979302582, 1659985974, 1333072010, 1395926189, 1345469121, 2314731054);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_add_scalar_wide()
        {
            uint a0 = (1473943965);
            uint3x2 b0 = uint3x2(1936000902, 925343902, 225370251, 1572924486, 2001194555, 1391317668);
            uint3x2 r0 = uint3x2(3409944867, 2399287867, 1699314216, 3046868451, 3475138520, 2865261633);
            TestUtils.AreEqual(a0 + b0, r0);

            uint a1 = (136118038);
            uint3x2 b1 = uint3x2(444753975, 2074990818, 460687149, 1198135619, 279061028, 593775297);
            uint3x2 r1 = uint3x2(580872013, 2211108856, 596805187, 1334253657, 415179066, 729893335);
            TestUtils.AreEqual(a1 + b1, r1);

            uint a2 = (424532120);
            uint3x2 b2 = uint3x2(908675040, 876636170, 709867944, 1792577509, 711770554, 1233918441);
            uint3x2 r2 = uint3x2(1333207160, 1301168290, 1134400064, 2217109629, 1136302674, 1658450561);
            TestUtils.AreEqual(a2 + b2, r2);

            uint a3 = (2127535094);
            uint3x2 b3 = uint3x2(522722338, 1814400879, 1677867823, 1983081877, 1906509250, 424528305);
            uint3x2 r3 = uint3x2(2650257432, 3941935973, 3805402917, 4110616971, 4034044344, 2552063399);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_sub_wide_wide()
        {
            uint3x2 a0 = uint3x2(1868671979, 1039843381, 1298473433, 1136791865, 175240759, 1588860513);
            uint3x2 b0 = uint3x2(1570102425, 1116042949, 1307533133, 57294526, 134828678, 1111898564);
            uint3x2 r0 = uint3x2(298569554, 4218767728, 4285907596, 1079497339, 40412081, 476961949);
            TestUtils.AreEqual(a0 - b0, r0);

            uint3x2 a1 = uint3x2(1450399140, 2133595841, 1740046500, 657512959, 1423325650, 278864421);
            uint3x2 b1 = uint3x2(452675165, 1844730313, 512848031, 924453828, 552946403, 783934119);
            uint3x2 r1 = uint3x2(997723975, 288865528, 1227198469, 4028026427, 870379247, 3789897598);
            TestUtils.AreEqual(a1 - b1, r1);

            uint3x2 a2 = uint3x2(1771875899, 1407726279, 223564929, 980621018, 868290646, 1969966556);
            uint3x2 b2 = uint3x2(77913045, 495222828, 711207747, 922411382, 734907931, 2119678714);
            uint3x2 r2 = uint3x2(1693962854, 912503451, 3807324478, 58209636, 133382715, 4145255138);
            TestUtils.AreEqual(a2 - b2, r2);

            uint3x2 a3 = uint3x2(1209857990, 2014347946, 1795362375, 446375911, 2050518174, 1917778262);
            uint3x2 b3 = uint3x2(814717039, 382823142, 748799197, 63546200, 1229362002, 513137254);
            uint3x2 r3 = uint3x2(395140951, 1631524804, 1046563178, 382829711, 821156172, 1404641008);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_sub_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1288845994, 655887040, 1531244714, 1226406872, 781343578, 1101968049);
            uint b0 = (16195101);
            uint3x2 r0 = uint3x2(1272650893, 639691939, 1515049613, 1210211771, 765148477, 1085772948);
            TestUtils.AreEqual(a0 - b0, r0);

            uint3x2 a1 = uint3x2(1008186509, 285218449, 2089960157, 1323018452, 809116994, 396220529);
            uint b1 = (500762411);
            uint3x2 r1 = uint3x2(507424098, 4079423334, 1589197746, 822256041, 308354583, 4190425414);
            TestUtils.AreEqual(a1 - b1, r1);

            uint3x2 a2 = uint3x2(1342637736, 809677454, 990465709, 259130138, 1135876784, 1418748403);
            uint b2 = (948654870);
            uint3x2 r2 = uint3x2(393982866, 4155989880, 41810839, 3605442564, 187221914, 470093533);
            TestUtils.AreEqual(a2 - b2, r2);

            uint3x2 a3 = uint3x2(559674210, 720477767, 479616263, 41168718, 2060304042, 267982041);
            uint b3 = (457487332);
            uint3x2 r3 = uint3x2(102186878, 262990435, 22128931, 3878648682, 1602816710, 4105462005);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_sub_scalar_wide()
        {
            uint a0 = (1882219675);
            uint3x2 b0 = uint3x2(1239052068, 981624121, 231031979, 368791143, 1127997491, 1469956291);
            uint3x2 r0 = uint3x2(643167607, 900595554, 1651187696, 1513428532, 754222184, 412263384);
            TestUtils.AreEqual(a0 - b0, r0);

            uint a1 = (1352108415);
            uint3x2 b1 = uint3x2(252406088, 798756155, 1165664847, 490545685, 150040657, 286361006);
            uint3x2 r1 = uint3x2(1099702327, 553352260, 186443568, 861562730, 1202067758, 1065747409);
            TestUtils.AreEqual(a1 - b1, r1);

            uint a2 = (1473760294);
            uint3x2 b2 = uint3x2(1837376960, 1807280648, 2106402623, 1329763512, 672191500, 1313234602);
            uint3x2 r2 = uint3x2(3931350630, 3961446942, 3662324967, 143996782, 801568794, 160525692);
            TestUtils.AreEqual(a2 - b2, r2);

            uint a3 = (1240091402);
            uint3x2 b3 = uint3x2(1294929405, 135030915, 44113712, 1587631264, 1611210200, 759680027);
            uint3x2 r3 = uint3x2(4240129293, 1105060487, 1195977690, 3947427434, 3923848498, 480411375);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mul_wide_wide()
        {
            uint3x2 a0 = uint3x2(1175935609, 1626539723, 279996667, 2111031627, 685568193, 1962710767);
            uint3x2 b0 = uint3x2(1809898573, 1960664942, 44842581, 1244459472, 324583419, 1868551095);
            uint3x2 r0 = uint3x2(3819319909, 2972794938, 3265504599, 3816237040, 4254600251, 1957159385);
            TestUtils.AreEqual(a0 * b0, r0);

            uint3x2 a1 = uint3x2(1115395046, 152633925, 1493478880, 699700164, 475889768, 1192754186);
            uint3x2 b1 = uint3x2(1741309699, 1510309193, 1799116733, 761205650, 1688324641, 1962825503);
            uint3x2 r1 = uint3x2(1257473458, 462837421, 2953543264, 2041565640, 3502742888, 1551559478);
            TestUtils.AreEqual(a1 * b1, r1);

            uint3x2 a2 = uint3x2(1163089838, 2065613335, 518297268, 490653429, 1259796407, 1433182720);
            uint3x2 b2 = uint3x2(1185791083, 534381819, 1256982490, 1250343185, 948571728, 769860956);
            uint3x2 r2 = uint3x2(47148474, 1120315533, 2226602312, 1160790853, 1230990128, 208943104);
            TestUtils.AreEqual(a2 * b2, r2);

            uint3x2 a3 = uint3x2(1842081955, 541439429, 617509486, 1977755498, 739429397, 731946172);
            uint3x2 b3 = uint3x2(1989848008, 142244192, 1686528968, 1012517137, 1241614931, 1904734139);
            uint3x2 r3 = uint3x2(3844005976, 3572516576, 1964896240, 4040218634, 1244691663, 1942618452);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mul_wide_scalar()
        {
            uint3x2 a0 = uint3x2(261135546, 971766724, 863155086, 735149234, 174946595, 657836706);
            uint b0 = (1844253884);
            uint3x2 r0 = uint3x2(77832344, 2171352048, 1857614920, 3328146104, 1111667124, 2437904120);
            TestUtils.AreEqual(a0 * b0, r0);

            uint3x2 a1 = uint3x2(1940866736, 937000174, 1113538456, 1262039542, 326741371, 1102277667);
            uint b1 = (620537339);
            uint3x2 r1 = uint3x2(3131686544, 1644880730, 1895846408, 1685031474, 2519817881, 1846646097);
            TestUtils.AreEqual(a1 * b1, r1);

            uint3x2 a2 = uint3x2(1900656642, 313110653, 1268446779, 1797229909, 117429572, 1667406709);
            uint b2 = (174463170);
            uint3x2 r2 = uint3x2(669622660, 1089566394, 1007034550, 3305575018, 3941989768, 300598954);
            TestUtils.AreEqual(a2 * b2, r2);

            uint3x2 a3 = uint3x2(634278255, 1056054287, 1442995733, 307706329, 1568700496, 1962476657);
            uint b3 = (238221445);
            uint3x2 r3 = uint3x2(2093078187, 2347047883, 2155428073, 834487741, 3891003792, 230606517);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mul_scalar_wide()
        {
            uint a0 = (2057129833);
            uint3x2 b0 = uint3x2(1333508928, 2103362674, 555404300, 702651820, 1875407260, 237922996);
            uint3x2 r0 = uint3x2(516459840, 2020065474, 3025233132, 2007875468, 3102850300, 1549488084);
            TestUtils.AreEqual(a0 * b0, r0);

            uint a1 = (1326594064);
            uint3x2 b1 = uint3x2(521612288, 1229721086, 423926724, 1922937387, 852227720, 1585292254);
            uint3x2 r1 = uint3x2(454213632, 2511106016, 103062592, 1960479408, 406661248, 1800326624);
            TestUtils.AreEqual(a1 * b1, r1);

            uint a2 = (461448775);
            uint3x2 b2 = uint3x2(879828777, 771011663, 1057882676, 532996060, 621007289, 67063537);
            uint3x2 r2 = uint3x2(1554561631, 1114684393, 694834284, 179355140, 107585615, 871869143);
            TestUtils.AreEqual(a2 * b2, r2);

            uint a3 = (882103331);
            uint3x2 b3 = uint3x2(1053336271, 1174306132, 1086691717, 1496127863, 2128375630, 2132186065);
            uint3x2 r3 = uint3x2(1159638605, 1490072188, 2844074287, 1435895621, 2786709418, 1736591763);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_div_wide_wide()
        {
            uint3x2 a0 = uint3x2(1088045904, 363581441, 2117293847, 43474130, 1437502728, 147730677);
            uint3x2 b0 = uint3x2(334000779, 1707521590, 48034914, 274954252, 1681174571, 619550611);
            uint3x2 r0 = uint3x2(3, 0, 44, 0, 0, 0);
            TestUtils.AreEqual(a0 / b0, r0);

            uint3x2 a1 = uint3x2(1746963064, 986496120, 989409859, 717654081, 697638750, 164833649);
            uint3x2 b1 = uint3x2(467348233, 1491029983, 459862277, 1092738758, 1011057052, 1614049909);
            uint3x2 r1 = uint3x2(3, 0, 2, 0, 0, 0);
            TestUtils.AreEqual(a1 / b1, r1);

            uint3x2 a2 = uint3x2(181829127, 1777427895, 2030007248, 154284884, 77444398, 1909917993);
            uint3x2 b2 = uint3x2(360356960, 1144441486, 1664322899, 266992285, 2033065666, 1553166258);
            uint3x2 r2 = uint3x2(0, 1, 1, 0, 0, 1);
            TestUtils.AreEqual(a2 / b2, r2);

            uint3x2 a3 = uint3x2(1855827887, 1140726205, 2064684631, 1006815877, 1874469680, 1224989065);
            uint3x2 b3 = uint3x2(444017400, 719972014, 948658676, 1745649713, 1075538185, 58851846);
            uint3x2 r3 = uint3x2(4, 1, 2, 0, 1, 20);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_div_wide_scalar()
        {
            uint3x2 a0 = uint3x2(698046988, 1172226457, 1341281323, 1895153499, 2041215936, 1389479447);
            uint b0 = (877940369);
            uint3x2 r0 = uint3x2(0, 1, 1, 2, 2, 1);
            TestUtils.AreEqual(a0 / b0, r0);

            uint3x2 a1 = uint3x2(1112377468, 1152385720, 1329193933, 1026467504, 1908759590, 379583730);
            uint b1 = (1428493086);
            uint3x2 r1 = uint3x2(0, 0, 0, 0, 1, 0);
            TestUtils.AreEqual(a1 / b1, r1);

            uint3x2 a2 = uint3x2(28412292, 382380097, 671398601, 998364247, 299274353, 203596848);
            uint b2 = (2127153910);
            uint3x2 r2 = uint3x2(0, 0, 0, 0, 0, 0);
            TestUtils.AreEqual(a2 / b2, r2);

            uint3x2 a3 = uint3x2(1271758211, 1288470572, 722675863, 819631958, 864064692, 1896633751);
            uint b3 = (1030388954);
            uint3x2 r3 = uint3x2(1, 1, 0, 0, 0, 1);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_div_scalar_wide()
        {
            uint a0 = (2021328826);
            uint3x2 b0 = uint3x2(874375696, 1507954497, 2127317467, 1203851704, 841281974, 376202331);
            uint3x2 r0 = uint3x2(2, 1, 0, 1, 2, 5);
            TestUtils.AreEqual(a0 / b0, r0);

            uint a1 = (1544089754);
            uint3x2 b1 = uint3x2(40402644, 1986071898, 2130326460, 1684745816, 1258341923, 1763081534);
            uint3x2 r1 = uint3x2(38, 0, 0, 0, 1, 0);
            TestUtils.AreEqual(a1 / b1, r1);

            uint a2 = (1178620704);
            uint3x2 b2 = uint3x2(4579859, 1407078950, 1217259005, 575524401, 1142938917, 1429440678);
            uint3x2 r2 = uint3x2(257, 0, 0, 2, 1, 0);
            TestUtils.AreEqual(a2 / b2, r2);

            uint a3 = (255894342);
            uint3x2 b3 = uint3x2(270430515, 1162688113, 1080280113, 166684975, 1606028217, 133041771);
            uint3x2 r3 = uint3x2(0, 0, 0, 1, 0, 1);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mod_wide_wide()
        {
            uint3x2 a0 = uint3x2(1404166133, 2132673500, 1226848706, 260867443, 1657891933, 1665617201);
            uint3x2 b0 = uint3x2(1451753818, 986752317, 426407306, 388266591, 1936904896, 1974281115);
            uint3x2 r0 = uint3x2(1404166133, 159168866, 374034094, 260867443, 1657891933, 1665617201);
            TestUtils.AreEqual(a0 % b0, r0);

            uint3x2 a1 = uint3x2(1193460322, 939577022, 349660242, 275322117, 2059991300, 66464083);
            uint3x2 b1 = uint3x2(2061811216, 1548000924, 1962740273, 442600258, 1214757164, 48882551);
            uint3x2 r1 = uint3x2(1193460322, 939577022, 349660242, 275322117, 845234136, 17581532);
            TestUtils.AreEqual(a1 % b1, r1);

            uint3x2 a2 = uint3x2(1210584015, 2128853048, 1886610218, 484061946, 1261597433, 620158848);
            uint3x2 b2 = uint3x2(150076096, 2140190639, 846749437, 1269758433, 1029725197, 1706820437);
            uint3x2 r2 = uint3x2(9975247, 2128853048, 193111344, 484061946, 231872236, 620158848);
            TestUtils.AreEqual(a2 % b2, r2);

            uint3x2 a3 = uint3x2(1274262355, 1760237377, 314335948, 1335579382, 2041362257, 1813460940);
            uint3x2 b3 = uint3x2(1372771540, 1995881439, 1201935603, 995011640, 348712039, 541812751);
            uint3x2 r3 = uint3x2(1274262355, 1760237377, 314335948, 340567742, 297802062, 188022687);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mod_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1161974084, 1730255826, 1307617556, 1348913399, 108127332, 158366308);
            uint b0 = (1619572929);
            uint3x2 r0 = uint3x2(1161974084, 110682897, 1307617556, 1348913399, 108127332, 158366308);
            TestUtils.AreEqual(a0 % b0, r0);

            uint3x2 a1 = uint3x2(608736703, 1124457489, 572642899, 1777547989, 568679511, 1047748248);
            uint b1 = (410222026);
            uint3x2 r1 = uint3x2(198514677, 304013437, 162420873, 136659885, 158457485, 227304196);
            TestUtils.AreEqual(a1 % b1, r1);

            uint3x2 a2 = uint3x2(753947810, 570275397, 965622832, 1450962286, 1106672888, 1451051118);
            uint b2 = (261245150);
            uint3x2 r2 = uint3x2(231457510, 47785097, 181887382, 144736536, 61692288, 144825368);
            TestUtils.AreEqual(a2 % b2, r2);

            uint3x2 a3 = uint3x2(2025083337, 1522014233, 1374852101, 2103351954, 1968921221, 35587335);
            uint b3 = (912627512);
            uint3x2 r3 = uint3x2(199828313, 609386721, 462224589, 278096930, 143666197, 35587335);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_mod_scalar_wide()
        {
            uint a0 = (732019691);
            uint3x2 b0 = uint3x2(1432618553, 1407625066, 2104173412, 787397289, 1250925010, 1942782982);
            uint3x2 r0 = uint3x2(732019691, 732019691, 732019691, 732019691, 732019691, 732019691);
            TestUtils.AreEqual(a0 % b0, r0);

            uint a1 = (895419737);
            uint3x2 b1 = uint3x2(1413458613, 1057786657, 895014416, 1411050342, 581995078, 1314657708);
            uint3x2 r1 = uint3x2(895419737, 895419737, 405321, 895419737, 313424659, 895419737);
            TestUtils.AreEqual(a1 % b1, r1);

            uint a2 = (988705005);
            uint3x2 b2 = uint3x2(893924184, 579424395, 788841281, 1894749534, 1578517841, 902966975);
            uint3x2 r2 = uint3x2(94780821, 409280610, 199863724, 988705005, 988705005, 85738030);
            TestUtils.AreEqual(a2 % b2, r2);

            uint a3 = (238684224);
            uint3x2 b3 = uint3x2(634711288, 168625436, 1937237642, 823496492, 450959406, 404691608);
            uint3x2 r3 = uint3x2(238684224, 70058788, 238684224, 238684224, 238684224, 238684224);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_plus()
        {
            uint3x2 a0 = uint3x2(1389572610, 784638699, 1994582731, 1916480804, 1916426865, 445404424);
            uint3x2 r0 = uint3x2(1389572610, 784638699, 1994582731, 1916480804, 1916426865, 445404424);
            TestUtils.AreEqual(+a0, r0);

            uint3x2 a1 = uint3x2(309068130, 790253154, 1469244349, 111908581, 702989834, 1214657768);
            uint3x2 r1 = uint3x2(309068130, 790253154, 1469244349, 111908581, 702989834, 1214657768);
            TestUtils.AreEqual(+a1, r1);

            uint3x2 a2 = uint3x2(648913468, 2052937846, 1848004046, 2025735104, 1679257084, 1132420338);
            uint3x2 r2 = uint3x2(648913468, 2052937846, 1848004046, 2025735104, 1679257084, 1132420338);
            TestUtils.AreEqual(+a2, r2);

            uint3x2 a3 = uint3x2(492383417, 196430696, 894375106, 1461639702, 835334114, 32791625);
            uint3x2 r3 = uint3x2(492383417, 196430696, 894375106, 1461639702, 835334114, 32791625);
            TestUtils.AreEqual(+a3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_neg()
        {
            uint3x2 a0 = uint3x2(718733484, 283062622, 1150527221, 531874537, 2059224113, 1889420629);
            uint3x2 r0 = uint3x2(3576233812, 4011904674, 3144440075, 3763092759, 2235743183, 2405546667);
            TestUtils.AreEqual(-a0, r0);

            uint3x2 a1 = uint3x2(1809777681, 2110619134, 1495661305, 946205741, 1731996287, 1872831707);
            uint3x2 r1 = uint3x2(2485189615, 2184348162, 2799305991, 3348761555, 2562971009, 2422135589);
            TestUtils.AreEqual(-a1, r1);

            uint3x2 a2 = uint3x2(1759886927, 2042911689, 2014670666, 1785634485, 1269836738, 1882699158);
            uint3x2 r2 = uint3x2(2535080369, 2252055607, 2280296630, 2509332811, 3025130558, 2412268138);
            TestUtils.AreEqual(-a2, r2);

            uint3x2 a3 = uint3x2(996075122, 1042326164, 829695960, 1615953054, 1848626634, 1688188403);
            uint3x2 r3 = uint3x2(3298892174, 3252641132, 3465271336, 2679014242, 2446340662, 2606778893);
            TestUtils.AreEqual(-a3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_prefix_inc()
        {
            uint3x2 a0 = uint3x2(1255324487, 1412620214, 2004729755, 364341497, 1001267099, 300799799);
            uint3x2 r0 = uint3x2(1255324488, 1412620215, 2004729756, 364341498, 1001267100, 300799800);
            TestUtils.AreEqual(++a0, r0);

            uint3x2 a1 = uint3x2(1826916366, 1403483584, 1126929701, 58299929, 1799441336, 1874383402);
            uint3x2 r1 = uint3x2(1826916367, 1403483585, 1126929702, 58299930, 1799441337, 1874383403);
            TestUtils.AreEqual(++a1, r1);

            uint3x2 a2 = uint3x2(1586837356, 852664432, 1531710577, 1423227601, 751290927, 1811943399);
            uint3x2 r2 = uint3x2(1586837357, 852664433, 1531710578, 1423227602, 751290928, 1811943400);
            TestUtils.AreEqual(++a2, r2);

            uint3x2 a3 = uint3x2(1231672495, 57984113, 1178315985, 507686985, 642839275, 1861070532);
            uint3x2 r3 = uint3x2(1231672496, 57984114, 1178315986, 507686986, 642839276, 1861070533);
            TestUtils.AreEqual(++a3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_postfix_inc()
        {
            uint3x2 a0 = uint3x2(482801952, 1525347232, 1327121509, 391425724, 696835538, 1167198637);
            uint3x2 r0 = uint3x2(482801952, 1525347232, 1327121509, 391425724, 696835538, 1167198637);
            TestUtils.AreEqual(a0++, r0);

            uint3x2 a1 = uint3x2(286946275, 1764804294, 358290724, 800117326, 1655297583, 1041844812);
            uint3x2 r1 = uint3x2(286946275, 1764804294, 358290724, 800117326, 1655297583, 1041844812);
            TestUtils.AreEqual(a1++, r1);

            uint3x2 a2 = uint3x2(312666038, 1116699556, 795715545, 982844920, 1207902920, 1961629484);
            uint3x2 r2 = uint3x2(312666038, 1116699556, 795715545, 982844920, 1207902920, 1961629484);
            TestUtils.AreEqual(a2++, r2);

            uint3x2 a3 = uint3x2(1941424958, 1328032701, 458681710, 818363470, 1780934301, 1208899882);
            uint3x2 r3 = uint3x2(1941424958, 1328032701, 458681710, 818363470, 1780934301, 1208899882);
            TestUtils.AreEqual(a3++, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_prefix_dec()
        {
            uint3x2 a0 = uint3x2(1786777392, 2114077793, 1678527347, 1458977374, 332157813, 1908999543);
            uint3x2 r0 = uint3x2(1786777391, 2114077792, 1678527346, 1458977373, 332157812, 1908999542);
            TestUtils.AreEqual(--a0, r0);

            uint3x2 a1 = uint3x2(569184702, 1653790314, 1727873646, 432424960, 510891085, 1806004859);
            uint3x2 r1 = uint3x2(569184701, 1653790313, 1727873645, 432424959, 510891084, 1806004858);
            TestUtils.AreEqual(--a1, r1);

            uint3x2 a2 = uint3x2(2055285618, 1974590384, 727840634, 1657883130, 774572143, 1276219624);
            uint3x2 r2 = uint3x2(2055285617, 1974590383, 727840633, 1657883129, 774572142, 1276219623);
            TestUtils.AreEqual(--a2, r2);

            uint3x2 a3 = uint3x2(774750407, 1547437444, 258724438, 118919226, 552422331, 1879324374);
            uint3x2 r3 = uint3x2(774750406, 1547437443, 258724437, 118919225, 552422330, 1879324373);
            TestUtils.AreEqual(--a3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_postfix_dec()
        {
            uint3x2 a0 = uint3x2(763128954, 1604006255, 851112563, 1351926085, 296277768, 1793717563);
            uint3x2 r0 = uint3x2(763128954, 1604006255, 851112563, 1351926085, 296277768, 1793717563);
            TestUtils.AreEqual(a0--, r0);

            uint3x2 a1 = uint3x2(400225071, 1767809423, 1966343832, 1639458045, 729159102, 1564789209);
            uint3x2 r1 = uint3x2(400225071, 1767809423, 1966343832, 1639458045, 729159102, 1564789209);
            TestUtils.AreEqual(a1--, r1);

            uint3x2 a2 = uint3x2(401130734, 423063416, 448523825, 2023756724, 121892713, 791108164);
            uint3x2 r2 = uint3x2(401130734, 423063416, 448523825, 2023756724, 121892713, 791108164);
            TestUtils.AreEqual(a2--, r2);

            uint3x2 a3 = uint3x2(1946569341, 571862090, 41814812, 2071269553, 1191516164, 1126029661);
            uint3x2 r3 = uint3x2(1946569341, 571862090, 41814812, 2071269553, 1191516164, 1126029661);
            TestUtils.AreEqual(a3--, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_and_wide_wide()
        {
            uint3x2 a0 = uint3x2(2092051178, 1746770686, 1029274525, 1475004282, 612016978, 797870200);
            uint3x2 b0 = uint3x2(272703892, 1322639335, 892833749, 1144239790, 1616750127, 886768760);
            uint3x2 r0 = uint3x2(268443776, 1209375462, 890309525, 1143113258, 542679554, 613023864);
            TestUtils.AreEqual(a0 & b0, r0);

            uint3x2 a1 = uint3x2(1438448989, 1307881465, 1061841715, 758104536, 792659253, 1952707562);
            uint3x2 b1 = uint3x2(151903875, 437958142, 1601934447, 709021151, 1161272974, 87355212);
            uint3x2 r1 = uint3x2(17619969, 135308792, 524943395, 671269336, 87491588, 69264200);
            TestUtils.AreEqual(a1 & b1, r1);

            uint3x2 a2 = uint3x2(591786804, 18587383, 2137260293, 1938728741, 2079117027, 1531731525);
            uint3x2 b2 = uint3x2(2003092747, 1175201405, 1818376664, 627815462, 1692040923, 418702231);
            uint3x2 r2 = uint3x2(591708416, 525941, 1818231040, 554345508, 1623740099, 407126533);
            TestUtils.AreEqual(a2 & b2, r2);

            uint3x2 a3 = uint3x2(679695184, 1294590416, 548710916, 1729598590, 949318613, 2072239038);
            uint3x2 b3 = uint3x2(1050351645, 1116669379, 631323443, 1395396662, 1633642673, 649593167);
            uint3x2 r3 = uint3x2(679677968, 1074332096, 547367424, 1124339766, 538271889, 578814222);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_and_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1539818086, 1174036358, 829722249, 278534026, 1883523687, 972630451);
            uint b0 = (1429236654);
            uint3x2 r0 = uint3x2(1358971430, 1160792966, 288361096, 269484938, 1342196262, 288369058);
            TestUtils.AreEqual(a0 & b0, r0);

            uint3x2 a1 = uint3x2(479408214, 1129809064, 1581024627, 182089936, 241631718, 710874038);
            uint b1 = (1980474728);
            uint3x2 r1 = uint3x2(335749184, 1107526696, 1443399008, 34218048, 100860256, 571146528);
            TestUtils.AreEqual(a1 & b1, r1);

            uint3x2 a2 = uint3x2(1975155852, 1337613880, 1334047680, 2064480518, 1322285560, 808609814);
            uint b2 = (1449409653);
            uint3x2 r2 = uint3x2(1411398660, 1176509488, 1174417472, 1376008196, 1178613872, 270542868);
            TestUtils.AreEqual(a2 & b2, r2);

            uint3x2 a3 = uint3x2(238335913, 1060535418, 914205556, 1274627743, 1613439939, 1950316859);
            uint b3 = (802616343);
            uint3x2 r3 = uint3x2(236237825, 790000658, 643080212, 198198295, 537010179, 605450259);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_and_scalar_wide()
        {
            uint a0 = (1464480071);
            uint3x2 b0 = uint3x2(880300166, 1801631129, 2146929359, 134501242, 560052329, 1883977874);
            uint3x2 r0 = uint3x2(340267014, 1128411393, 1463943239, 4418, 20983873, 1347039234);
            TestUtils.AreEqual(a0 & b0, r0);

            uint a1 = (1013494998);
            uint3x2 b1 = uint3x2(1922782264, 691181116, 462206052, 446227614, 733622820, 154650269);
            uint3x2 r1 = uint3x2(805835792, 673223700, 403223620, 403219606, 673722372, 136348820);
            TestUtils.AreEqual(a1 & b1, r1);

            uint a2 = (1040709037);
            uint3x2 b2 = uint3x2(872751594, 1748058103, 515699587, 1854871563, 684039719, 435845623);
            uint3x2 r2 = uint3x2(872751528, 671167909, 503640449, 772214793, 671454245, 402813349);
            TestUtils.AreEqual(a2 & b2, r2);

            uint a3 = (1477579741);
            uint3x2 b3 = uint3x2(624937918, 987459778, 1763643001, 1468764252, 80425994, 1974457780);
            uint3x2 r3 = uint3x2(1180572, 403837120, 1209139801, 1342312540, 135176, 1342312852);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_or_wide_wide()
        {
            uint3x2 a0 = uint3x2(734971681, 170686390, 1266964099, 1460491362, 1803179461, 768462149);
            uint3x2 b0 = uint3x2(855541034, 1662326443, 1355326851, 2034950208, 350174433, 267121140);
            uint3x2 r0 = uint3x2(1006552875, 1799190463, 1540159363, 2135946338, 2147450341, 804257269);
            TestUtils.AreEqual(a0 | b0, r0);

            uint3x2 a1 = uint3x2(987469872, 438875025, 1128872651, 795335618, 1529817033, 741387702);
            uint3x2 b1 = uint3x2(1311095923, 1505207657, 504611275, 741405442, 29985341, 1349904874);
            uint3x2 r1 = uint3x2(2130689139, 1539291129, 1599863755, 796392386, 1542434813, 2088103422);
            TestUtils.AreEqual(a1 | b1, r1);

            uint3x2 a2 = uint3x2(1220165008, 1338127916, 1489866234, 179365479, 271887939, 949829005);
            uint3x2 b2 = uint3x2(2075459701, 1867309176, 1329238130, 1905614698, 243380332, 2030947165);
            uint3x2 r2 = uint3x2(2076130805, 1875834492, 1610587642, 2075524975, 515227247, 2040397789);
            TestUtils.AreEqual(a2 | b2, r2);

            uint3x2 a3 = uint3x2(1924295483, 1565617278, 2114237895, 107080877, 1139095362, 352536950);
            uint3x2 b3 = uint3x2(1446681429, 2018905151, 585548776, 310314990, 2084079897, 262706040);
            uint3x2 r3 = uint3x2(1991965567, 2102881407, 2129065967, 377483247, 2147336027, 531356542);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_or_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1734012999, 667885144, 1145828203, 697078394, 548056872, 1693193261);
            uint b0 = (724265524);
            uint3x2 r0 = uint3x2(1870396023, 804224636, 1869347711, 732953214, 732688188, 1877966397);
            TestUtils.AreEqual(a0 | b0, r0);

            uint3x2 a1 = uint3x2(982993821, 1721498502, 629916984, 1306607927, 1103396649, 629860201);
            uint b1 = (1923524974);
            uint3x2 r1 = uint3x2(2058873855, 1992293358, 2008018302, 2145905023, 1944518511, 2007953263);
            TestUtils.AreEqual(a1 | b1, r1);

            uint3x2 a2 = uint3x2(748158308, 1149265831, 591994749, 1915156047, 1655990044, 854989838);
            uint b2 = (1434379189);
            uint3x2 r2 = uint3x2(2113929205, 1442768823, 2004877309, 2004809727, 2013194173, 2013200319);
            TestUtils.AreEqual(a2 | b2, r2);

            uint3x2 a3 = uint3x2(116720856, 1529825596, 1732308386, 1265510112, 1772725577, 1966044680);
            uint b3 = (393888236);
            uint3x2 r3 = uint3x2(402605564, 1602177532, 2004545006, 1602119660, 2147214829, 2004842476);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_or_scalar_wide()
        {
            uint a0 = (1944842696);
            uint3x2 b0 = uint3x2(1797946902, 1995080562, 1009785533, 2078864395, 1738258290, 2078839688);
            uint3x2 r0 = uint3x2(2079064030, 2011952122, 2147220477, 2079061451, 2013001722, 2079060936);
            TestUtils.AreEqual(a0 | b0, r0);

            uint a1 = (182771906);
            uint3x2 b1 = uint3x2(331104563, 1016101895, 1555585463, 344959457, 1773844766, 2065533499);
            uint3x2 r1 = uint3x2(469557747, 1056242887, 1593637367, 519039459, 1811872222, 2080238331);
            TestUtils.AreEqual(a1 | b1, r1);

            uint a2 = (930917837);
            uint3x2 b2 = uint3x2(660708795, 294373756, 677858240, 1983817531, 2008476971, 1783619227);
            uint3x2 r2 = uint3x2(930987519, 939519485, 1065349069, 2004791295, 2013195759, 2139095007);
            TestUtils.AreEqual(a2 | b2, r2);

            uint a3 = (943797701);
            uint3x2 b3 = uint3x2(741485891, 1611993557, 1139962120, 472265873, 1159614643, 1216369159);
            uint3x2 r3 = uint3x2(1014185415, 2018850261, 2079552973, 1013396949, 2103408119, 2025945031);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_xor_wide_wide()
        {
            uint3x2 a0 = uint3x2(1451207246, 1326937873, 1723637117, 1703580819, 248456219, 102413373);
            uint3x2 b0 = uint3x2(973506398, 229917169, 115811768, 824430321, 1106935191, 1150807945);
            uint3x2 r0 = uint3x2(1819880720, 1117992672, 1616623813, 1420384866, 1328896396, 1116560308);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint3x2 a1 = uint3x2(1112748052, 786343099, 1705703147, 1153897995, 706969967, 856434388);
            uint3x2 b1 = uint3x2(1096766695, 405353279, 1241418803, 1943592644, 817552063, 980538734);
            uint3x2 r1 = uint3x2(51143923, 922195844, 743733976, 924829903, 446258128, 159249338);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint3x2 a2 = uint3x2(1429965951, 206758510, 530227784, 30367516, 781820050, 350072558);
            uint3x2 b2 = uint3x2(1055597865, 93654543, 1866100663, 428258142, 1532858506, 2045421737);
            uint3x2 r2 = uint3x2(1808836950, 164097121, 1889586687, 407497794, 1975791640, 1832322631);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint3x2 a3 = uint3x2(1506701192, 1749550432, 801802251, 881150186, 2119789506, 124082522);
            uint3x2 b3 = uint3x2(1774747197, 452373668, 118283764, 129561090, 915948317, 583510087);
            uint3x2 r3 = uint3x2(805704117, 1925097924, 684086783, 859683560, 1220618463, 631435549);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_xor_wide_scalar()
        {
            uint3x2 a0 = uint3x2(1168710170, 1910166247, 770450475, 137053244, 294543551, 1408449906);
            uint b0 = (1652551354);
            uint3x2 r0 = uint3x2(668398752, 329595997, 1335085713, 1783933574, 1945210373, 831312840);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint3x2 a1 = uint3x2(1818436467, 1868775761, 2129912193, 2002455346, 1128536481, 137121619);
            uint b1 = (1927634471);
            uint3x2 r1 = uint3x2(512130388, 495329142, 202817446, 96359701, 832653190, 2059997556);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint3x2 a2 = uint3x2(217103701, 672445107, 1736096264, 792848316, 1734728632, 1569700130);
            uint b2 = (2089471351);
            uint3x2 r2 = uint3x2(1887072290, 1419673540, 468744063, 1405823691, 468653775, 554005589);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint3x2 a3 = uint3x2(693181400, 1902550747, 838201645, 1371411220, 813904326, 1675805514);
            uint b3 = (1591621356);
            uint3x2 r3 = uint3x2(2005871924, 800630839, 1865140161, 257959416, 1851590442, 1027405222);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_xor_scalar_wide()
        {
            uint a0 = (1194539731);
            uint3x2 b0 = uint3x2(1838033352, 576935253, 399395950, 250856040, 1425907707, 1076687299);
            uint3x2 r0 = uint3x2(717034267, 1699770246, 1358788285, 1237383355, 332309800, 119524112);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint a1 = (983484392);
            uint3x2 b1 = uint3x2(2124473834, 2078261486, 1921195479, 95097761, 573992422, 1605464512);
            uint3x2 r1 = uint3x2(1144922626, 1094780678, 1209915967, 1060492361, 413706766, 1697625640);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint a2 = (619598441);
            uint3x2 b2 = uint3x2(2142716785, 1152008011, 2146366522, 1906443135, 1183476844, 595094127);
            uint3x2 r2 = uint3x2(1532563736, 1615097122, 1526769235, 1431064854, 1650736645, 127285254);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint a3 = (477679389);
            uint3x2 b3 = uint3x2(1422748994, 467245707, 113755677, 1824784547, 271553025, 984124685);
            uint3x2 r3 = uint3x2(1219863135, 128013718, 448727296, 1891422142, 207052060, 651182608);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_left_shift()
        {
            uint3x2 a0 = uint3x2(931909748, 24051129, 764104297, 615327136, 915651018, 778230483);
            int b0 = (633406437);
            uint3x2 r0 = uint3x2(4051308160, 769636128, 2976501024, 2510599168, 3531028800, 3428538976);
            TestUtils.AreEqual(a0 << b0, r0);

            uint3x2 a1 = uint3x2(1053065817, 258942729, 1285562176, 1971396937, 32966442, 1409592718);
            int b1 = (1251270776);
            uint3x2 r1 = uint3x2(1493172224, 150994944, 1073741824, 1224736768, 704643072, 2382364672);
            TestUtils.AreEqual(a1 << b1, r1);

            uint3x2 a2 = uint3x2(538213441, 524937488, 624466118, 1111935176, 465262380, 936874837);
            int b2 = (2054530579);
            uint3x2 r2 = uint3x2(3792175104, 1216348160, 3325034496, 1178599424, 3110076416, 2594701312);
            TestUtils.AreEqual(a2 << b2, r2);

            uint3x2 a3 = uint3x2(1392283667, 949546679, 1123185955, 311157834, 634963054, 28333286);
            int b3 = (1002534458);
            uint3x2 r3 = uint3x2(1275068416, 3690987520, 2348810240, 671088640, 3087007744, 2550136832);
            TestUtils.AreEqual(a3 << b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_right_shift()
        {
            uint3x2 a0 = uint3x2(1366397886, 1724049991, 102473945, 171782889, 1292455651, 86277781);
            int b0 = (1757774778);
            uint3x2 r0 = uint3x2(20, 25, 1, 2, 19, 1);
            TestUtils.AreEqual(a0 >> b0, r0);

            uint3x2 a1 = uint3x2(56874046, 1893257536, 2046727266, 1170864679, 1264893071, 1265324047);
            int b1 = (1261184742);
            uint3x2 r1 = uint3x2(888656, 29582149, 31980113, 18294760, 19763954, 19770688);
            TestUtils.AreEqual(a1 >> b1, r1);

            uint3x2 a2 = uint3x2(993515717, 186426076, 562082206, 452386814, 338639704, 1449581600);
            int b2 = (320091418);
            uint3x2 r2 = uint3x2(14, 2, 8, 6, 5, 21);
            TestUtils.AreEqual(a2 >> b2, r2);

            uint3x2 a3 = uint3x2(1825350371, 374423720, 164572160, 1239322828, 1697725793, 2116573268);
            int b3 = (16947721);
            uint3x2 r3 = uint3x2(3565137, 731296, 321430, 2420552, 3315870, 4133932);
            TestUtils.AreEqual(a3 >> b3, r3);
        }

        [TestCompiler]
        public static void uint3x2_operator_bitwise_not()
        {
            uint3x2 a0 = uint3x2(1581459784, 813914639, 1110317406, 876503210, 707106370, 356629770);
            uint3x2 r0 = uint3x2(2713507511, 3481052656, 3184649889, 3418464085, 3587860925, 3938337525);
            TestUtils.AreEqual(~a0, r0);

            uint3x2 a1 = uint3x2(813009756, 1610491464, 214532408, 476264684, 776399159, 22668443);
            uint3x2 r1 = uint3x2(3481957539, 2684475831, 4080434887, 3818702611, 3518568136, 4272298852);
            TestUtils.AreEqual(~a1, r1);

            uint3x2 a2 = uint3x2(246932821, 1114736666, 1596002861, 620656125, 1531048177, 2091343919);
            uint3x2 r2 = uint3x2(4048034474, 3180230629, 2698964434, 3674311170, 2763919118, 2203623376);
            TestUtils.AreEqual(~a2, r2);

            uint3x2 a3 = uint3x2(1782155829, 476668865, 601977771, 173406346, 1280862234, 1136385834);
            uint3x2 r3 = uint3x2(2512811466, 3818298430, 3692989524, 4121560949, 3014105061, 3158581461);
            TestUtils.AreEqual(~a3, r3);
        }


    }
}
