//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using static Unity.Mathematics.math;
using Burst.Compiler.IL.Tests;

namespace Unity.Mathematics.Tests
{
    [TestFixture]
    public class TestUint2
    {
        [TestCompiler]
        public static void uint2_zero()
        {
            TestUtils.AreEqual(uint2.zero.x, 0u);
            TestUtils.AreEqual(uint2.zero.y, 0u);
        }

        [TestCompiler]
        public static void uint2_constructor()
        {
            uint2 a = new uint2(1, 2);
            TestUtils.AreEqual(a.x, 1);
            TestUtils.AreEqual(a.y, 2);
        }

        [TestCompiler]
        public static void uint2_scalar_constructor()
        {
            uint2 a = new uint2(17u);
            TestUtils.AreEqual(a.x, 17u);
            TestUtils.AreEqual(a.y, 17u);
        }

        [TestCompiler]
        public static void uint2_static_constructor()
        {
            uint2 a = uint2(1, 2);
            TestUtils.AreEqual(a.x, 1);
            TestUtils.AreEqual(a.y, 2);
        }

        [TestCompiler]
        public static void uint2_static_scalar_constructor()
        {
            uint2 a = uint2(17u);
            TestUtils.AreEqual(a.x, 17u);
            TestUtils.AreEqual(a.y, 17u);
        }

        [TestCompiler]
        public static void uint2_operator_equal_wide_wide()
        {
            uint2 a0 = uint2(1769459654, 197796492);
            uint2 b0 = uint2(179132783, 1978336870);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint2 a1 = uint2(154243692, 952126595);
            uint2 b1 = uint2(1626004111, 424899921);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint2 a2 = uint2(689725190, 1225413740);
            uint2 b2 = uint2(1894146793, 91777081);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint2 a3 = uint2(459892608, 693366823);
            uint2 b3 = uint2(256037971, 669679301);
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_equal_wide_scalar()
        {
            uint2 a0 = uint2(1759724257, 1997468592);
            uint b0 = (1791891760);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint2 a1 = uint2(143140702, 1986782555);
            uint b1 = (1756461805);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint2 a2 = uint2(1196177899, 1864507830);
            uint b2 = (238163080);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint2 a3 = uint2(2008027469, 880022489);
            uint b3 = (1036427796);
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_equal_scalar_wide()
        {
            uint a0 = (1977155329);
            uint2 b0 = uint2(162052257, 1291280073);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            uint a1 = (522114153);
            uint2 b1 = uint2(602804987, 1501793202);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            uint a2 = (1485975269);
            uint2 b2 = uint2(182962739, 2054056581);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            uint a3 = (978460589);
            uint2 b3 = uint2(1363550636, 1453456227);
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_not_equal_wide_wide()
        {
            uint2 a0 = uint2(1114120377, 1328200685);
            uint2 b0 = uint2(551411861, 1033798228);
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint2 a1 = uint2(2055858397, 628379191);
            uint2 b1 = uint2(1752427499, 1692279987);
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint2 a2 = uint2(212580972, 2138118298);
            uint2 b2 = uint2(40976337, 724601100);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint2 a3 = uint2(1183215634, 403403153);
            uint2 b3 = uint2(1957052399, 1257584257);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_not_equal_wide_scalar()
        {
            uint2 a0 = uint2(197085580, 1559123934);
            uint b0 = (641022627);
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint2 a1 = uint2(89174026, 285035719);
            uint b1 = (874566733);
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint2 a2 = uint2(175911184, 882200899);
            uint b2 = (2107486277);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint2 a3 = uint2(1242391870, 215397387);
            uint b3 = (812875165);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_not_equal_scalar_wide()
        {
            uint a0 = (1823145268);
            uint2 b0 = uint2(1478442612, 395956316);
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            uint a1 = (1021050384);
            uint2 b1 = uint2(506455754, 120739710);
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            uint a2 = (111528848);
            uint2 b2 = uint2(497993131, 1341426941);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            uint a3 = (981702603);
            uint2 b3 = uint2(697361127, 2118726847);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_wide_wide()
        {
            uint2 a0 = uint2(2096784746, 6455590);
            uint2 b0 = uint2(2023955832, 814050279);
            bool2 r0 = bool2(false, true);
            TestUtils.AreEqual(a0 < b0, r0);

            uint2 a1 = uint2(1186728125, 2004430503);
            uint2 b1 = uint2(2107113757, 1984877677);
            bool2 r1 = bool2(true, false);
            TestUtils.AreEqual(a1 < b1, r1);

            uint2 a2 = uint2(903707670, 1290095569);
            uint2 b2 = uint2(229711986, 65531143);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 < b2, r2);

            uint2 a3 = uint2(33135516, 1136659156);
            uint2 b3 = uint2(1739169538, 1442465278);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_wide_scalar()
        {
            uint2 a0 = uint2(1111812659, 215280083);
            uint b0 = (1393181832);
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 < b0, r0);

            uint2 a1 = uint2(1452878573, 1552447661);
            uint b1 = (685443717);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 < b1, r1);

            uint2 a2 = uint2(1334052403, 428772023);
            uint b2 = (1631047060);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 < b2, r2);

            uint2 a3 = uint2(2107896094, 1349894445);
            uint b3 = (1150022920);
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_scalar_wide()
        {
            uint a0 = (1947585822);
            uint2 b0 = uint2(852724905, 257426229);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 < b0, r0);

            uint a1 = (1931155895);
            uint2 b1 = uint2(891206688, 1637228394);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 < b1, r1);

            uint a2 = (87657529);
            uint2 b2 = uint2(1642732032, 716549196);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 < b2, r2);

            uint a3 = (745331149);
            uint2 b3 = uint2(1073136377, 1224927266);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 < b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_wide_wide()
        {
            uint2 a0 = uint2(679407976, 1565104964);
            uint2 b0 = uint2(1037249636, 948878199);
            bool2 r0 = bool2(false, true);
            TestUtils.AreEqual(a0 > b0, r0);

            uint2 a1 = uint2(955659700, 1579068177);
            uint2 b1 = uint2(1022811823, 1540122195);
            bool2 r1 = bool2(false, true);
            TestUtils.AreEqual(a1 > b1, r1);

            uint2 a2 = uint2(2125437566, 437413511);
            uint2 b2 = uint2(639273951, 1840348368);
            bool2 r2 = bool2(true, false);
            TestUtils.AreEqual(a2 > b2, r2);

            uint2 a3 = uint2(433042806, 86523161);
            uint2 b3 = uint2(1458722938, 1025338066);
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_wide_scalar()
        {
            uint2 a0 = uint2(2057056127, 328369940);
            uint b0 = (1496952827);
            bool2 r0 = bool2(true, false);
            TestUtils.AreEqual(a0 > b0, r0);

            uint2 a1 = uint2(977884645, 1805071634);
            uint b1 = (1927653020);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 > b1, r1);

            uint2 a2 = uint2(1951495065, 309800711);
            uint b2 = (187170445);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 > b2, r2);

            uint2 a3 = uint2(1984248926, 1448725978);
            uint b3 = (538865160);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_scalar_wide()
        {
            uint a0 = (1362109003);
            uint2 b0 = uint2(142885648, 1660635591);
            bool2 r0 = bool2(true, false);
            TestUtils.AreEqual(a0 > b0, r0);

            uint a1 = (104009698);
            uint2 b1 = uint2(485042379, 1326894883);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 > b1, r1);

            uint a2 = (1007324999);
            uint2 b2 = uint2(1835906302, 1625555804);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 > b2, r2);

            uint a3 = (745829307);
            uint2 b3 = uint2(1212896249, 438032966);
            bool2 r3 = bool2(false, true);
            TestUtils.AreEqual(a3 > b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_equal_wide_wide()
        {
            uint2 a0 = uint2(1772193278, 1575696890);
            uint2 b0 = uint2(1170485947, 280845724);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint2 a1 = uint2(1129461478, 1160757899);
            uint2 b1 = uint2(94836958, 710231911);
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint2 a2 = uint2(732614174, 505407897);
            uint2 b2 = uint2(62412740, 1458247289);
            bool2 r2 = bool2(false, true);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint2 a3 = uint2(845181177, 1895996546);
            uint2 b3 = uint2(1910665214, 806067482);
            bool2 r3 = bool2(true, false);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_equal_wide_scalar()
        {
            uint2 a0 = uint2(1331309222, 478791836);
            uint b0 = (692177811);
            bool2 r0 = bool2(false, true);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint2 a1 = uint2(467984397, 412606484);
            uint b1 = (684816797);
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint2 a2 = uint2(1660050607, 537773128);
            uint b2 = (406933135);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint2 a3 = uint2(300305325, 639098736);
            uint b3 = (795892530);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_less_equal_scalar_wide()
        {
            uint a0 = (368122142);
            uint2 b0 = uint2(1602136857, 1025804484);
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 <= b0, r0);

            uint a1 = (572719917);
            uint2 b1 = uint2(1670730995, 322281926);
            bool2 r1 = bool2(true, false);
            TestUtils.AreEqual(a1 <= b1, r1);

            uint a2 = (2056320987);
            uint2 b2 = uint2(153014038, 660460911);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 <= b2, r2);

            uint a3 = (302838143);
            uint2 b3 = uint2(771971953, 260376717);
            bool2 r3 = bool2(true, false);
            TestUtils.AreEqual(a3 <= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_equal_wide_wide()
        {
            uint2 a0 = uint2(1374979366, 545879935);
            uint2 b0 = uint2(215438260, 895664604);
            bool2 r0 = bool2(true, false);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint2 a1 = uint2(1322414052, 1123804185);
            uint2 b1 = uint2(2141461196, 945533420);
            bool2 r1 = bool2(false, true);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint2 a2 = uint2(1251232279, 768853165);
            uint2 b2 = uint2(1365701491, 1010346143);
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint2 a3 = uint2(582070144, 1263454123);
            uint2 b3 = uint2(1515687794, 1130396256);
            bool2 r3 = bool2(false, true);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_equal_wide_scalar()
        {
            uint2 a0 = uint2(328496099, 1711908264);
            uint b0 = (781823478);
            bool2 r0 = bool2(false, true);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint2 a1 = uint2(1881414926, 159789484);
            uint b1 = (520188393);
            bool2 r1 = bool2(true, false);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint2 a2 = uint2(1339033201, 598204379);
            uint b2 = (1235245220);
            bool2 r2 = bool2(true, false);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint2 a3 = uint2(627782248, 1050513019);
            uint b3 = (207207443);
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_greater_equal_scalar_wide()
        {
            uint a0 = (557688741);
            uint2 b0 = uint2(1371865141, 1033269674);
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 >= b0, r0);

            uint a1 = (755002243);
            uint2 b1 = uint2(1765845791, 602301797);
            bool2 r1 = bool2(false, true);
            TestUtils.AreEqual(a1 >= b1, r1);

            uint a2 = (2020815501);
            uint2 b2 = uint2(159421708, 1924937716);
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 >= b2, r2);

            uint a3 = (394222366);
            uint2 b3 = uint2(1704680025, 357243706);
            bool2 r3 = bool2(false, true);
            TestUtils.AreEqual(a3 >= b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_add_wide_wide()
        {
            uint2 a0 = uint2(225914922, 622990175);
            uint2 b0 = uint2(1983696599, 1828130431);
            uint2 r0 = uint2(2209611521, 2451120606);
            TestUtils.AreEqual(a0 + b0, r0);

            uint2 a1 = uint2(729236185, 1783579909);
            uint2 b1 = uint2(1955603448, 200546650);
            uint2 r1 = uint2(2684839633, 1984126559);
            TestUtils.AreEqual(a1 + b1, r1);

            uint2 a2 = uint2(1708861806, 380354128);
            uint2 b2 = uint2(731457904, 998973978);
            uint2 r2 = uint2(2440319710, 1379328106);
            TestUtils.AreEqual(a2 + b2, r2);

            uint2 a3 = uint2(1029189209, 1403268164);
            uint2 b3 = uint2(1620597307, 1031552425);
            uint2 r3 = uint2(2649786516, 2434820589);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_add_wide_scalar()
        {
            uint2 a0 = uint2(395461163, 1754549897);
            uint b0 = (420967776);
            uint2 r0 = uint2(816428939, 2175517673);
            TestUtils.AreEqual(a0 + b0, r0);

            uint2 a1 = uint2(490977997, 111030504);
            uint b1 = (82076982);
            uint2 r1 = uint2(573054979, 193107486);
            TestUtils.AreEqual(a1 + b1, r1);

            uint2 a2 = uint2(1375953840, 1386457204);
            uint b2 = (372298610);
            uint2 r2 = uint2(1748252450, 1758755814);
            TestUtils.AreEqual(a2 + b2, r2);

            uint2 a3 = uint2(259325464, 1057574070);
            uint b3 = (1709985405);
            uint2 r3 = uint2(1969310869, 2767559475);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_add_scalar_wide()
        {
            uint a0 = (1473943965);
            uint2 b0 = uint2(1936000902, 925343902);
            uint2 r0 = uint2(3409944867, 2399287867);
            TestUtils.AreEqual(a0 + b0, r0);

            uint a1 = (225370251);
            uint2 b1 = uint2(1572924486, 2001194555);
            uint2 r1 = uint2(1798294737, 2226564806);
            TestUtils.AreEqual(a1 + b1, r1);

            uint a2 = (1391317668);
            uint2 b2 = uint2(136118038, 444753975);
            uint2 r2 = uint2(1527435706, 1836071643);
            TestUtils.AreEqual(a2 + b2, r2);

            uint a3 = (2074990818);
            uint2 b3 = uint2(460687149, 1198135619);
            uint2 r3 = uint2(2535677967, 3273126437);
            TestUtils.AreEqual(a3 + b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_sub_wide_wide()
        {
            uint2 a0 = uint2(1868671979, 1039843381);
            uint2 b0 = uint2(1570102425, 1116042949);
            uint2 r0 = uint2(298569554, 4218767728);
            TestUtils.AreEqual(a0 - b0, r0);

            uint2 a1 = uint2(1298473433, 1136791865);
            uint2 b1 = uint2(1307533133, 57294526);
            uint2 r1 = uint2(4285907596, 1079497339);
            TestUtils.AreEqual(a1 - b1, r1);

            uint2 a2 = uint2(175240759, 1588860513);
            uint2 b2 = uint2(134828678, 1111898564);
            uint2 r2 = uint2(40412081, 476961949);
            TestUtils.AreEqual(a2 - b2, r2);

            uint2 a3 = uint2(1450399140, 2133595841);
            uint2 b3 = uint2(452675165, 1844730313);
            uint2 r3 = uint2(997723975, 288865528);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_sub_wide_scalar()
        {
            uint2 a0 = uint2(1288845994, 655887040);
            uint b0 = (16195101);
            uint2 r0 = uint2(1272650893, 639691939);
            TestUtils.AreEqual(a0 - b0, r0);

            uint2 a1 = uint2(1531244714, 781343578);
            uint b1 = (1226406872);
            uint2 r1 = uint2(304837842, 3849904002);
            TestUtils.AreEqual(a1 - b1, r1);

            uint2 a2 = uint2(1101968049, 500762411);
            uint b2 = (1008186509);
            uint2 r2 = uint2(93781540, 3787543198);
            TestUtils.AreEqual(a2 - b2, r2);

            uint2 a3 = uint2(285218449, 1323018452);
            uint b3 = (2089960157);
            uint2 r3 = uint2(2490225588, 3528025591);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_sub_scalar_wide()
        {
            uint a0 = (1882219675);
            uint2 b0 = uint2(1239052068, 981624121);
            uint2 r0 = uint2(643167607, 900595554);
            TestUtils.AreEqual(a0 - b0, r0);

            uint a1 = (231031979);
            uint2 b1 = uint2(368791143, 1127997491);
            uint2 r1 = uint2(4157208132, 3398001784);
            TestUtils.AreEqual(a1 - b1, r1);

            uint a2 = (1469956291);
            uint2 b2 = uint2(1352108415, 252406088);
            uint2 r2 = uint2(117847876, 1217550203);
            TestUtils.AreEqual(a2 - b2, r2);

            uint a3 = (798756155);
            uint2 b3 = uint2(1165664847, 490545685);
            uint2 r3 = uint2(3928058604, 308210470);
            TestUtils.AreEqual(a3 - b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mul_wide_wide()
        {
            uint2 a0 = uint2(1175935609, 1626539723);
            uint2 b0 = uint2(1809898573, 1960664942);
            uint2 r0 = uint2(3819319909, 2972794938);
            TestUtils.AreEqual(a0 * b0, r0);

            uint2 a1 = uint2(279996667, 2111031627);
            uint2 b1 = uint2(44842581, 1244459472);
            uint2 r1 = uint2(3265504599, 3816237040);
            TestUtils.AreEqual(a1 * b1, r1);

            uint2 a2 = uint2(685568193, 1962710767);
            uint2 b2 = uint2(324583419, 1868551095);
            uint2 r2 = uint2(4254600251, 1957159385);
            TestUtils.AreEqual(a2 * b2, r2);

            uint2 a3 = uint2(1115395046, 152633925);
            uint2 b3 = uint2(1741309699, 1510309193);
            uint2 r3 = uint2(1257473458, 462837421);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mul_wide_scalar()
        {
            uint2 a0 = uint2(261135546, 971766724);
            uint b0 = (1844253884);
            uint2 r0 = uint2(77832344, 2171352048);
            TestUtils.AreEqual(a0 * b0, r0);

            uint2 a1 = uint2(863155086, 174946595);
            uint b1 = (735149234);
            uint2 r1 = uint2(3316097212, 224276054);
            TestUtils.AreEqual(a1 * b1, r1);

            uint2 a2 = uint2(657836706, 620537339);
            uint b2 = (1940866736);
            uint2 r2 = uint2(4112620384, 3131686544);
            TestUtils.AreEqual(a2 * b2, r2);

            uint2 a3 = uint2(937000174, 1262039542);
            uint b3 = (1113538456);
            uint2 r3 = uint2(1731379024, 3012244496);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mul_scalar_wide()
        {
            uint a0 = (2057129833);
            uint2 b0 = uint2(1333508928, 2103362674);
            uint2 r0 = uint2(516459840, 2020065474);
            TestUtils.AreEqual(a0 * b0, r0);

            uint a1 = (555404300);
            uint2 b1 = uint2(702651820, 1875407260);
            uint2 r1 = uint2(4021318672, 2646975312);
            TestUtils.AreEqual(a1 * b1, r1);

            uint a2 = (237922996);
            uint2 b2 = uint2(1326594064, 521612288);
            uint2 r2 = uint2(384174912, 1552084992);
            TestUtils.AreEqual(a2 * b2, r2);

            uint a3 = (1229721086);
            uint2 b3 = uint2(423926724, 1922937387);
            uint2 r3 = uint2(2955640952, 3796301226);
            TestUtils.AreEqual(a3 * b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_div_wide_wide()
        {
            uint2 a0 = uint2(1088045904, 363581441);
            uint2 b0 = uint2(334000779, 1707521590);
            uint2 r0 = uint2(3, 0);
            TestUtils.AreEqual(a0 / b0, r0);

            uint2 a1 = uint2(2117293847, 43474130);
            uint2 b1 = uint2(48034914, 274954252);
            uint2 r1 = uint2(44, 0);
            TestUtils.AreEqual(a1 / b1, r1);

            uint2 a2 = uint2(1437502728, 147730677);
            uint2 b2 = uint2(1681174571, 619550611);
            uint2 r2 = uint2(0, 0);
            TestUtils.AreEqual(a2 / b2, r2);

            uint2 a3 = uint2(1746963064, 986496120);
            uint2 b3 = uint2(467348233, 1491029983);
            uint2 r3 = uint2(3, 0);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_div_wide_scalar()
        {
            uint2 a0 = uint2(698046988, 1172226457);
            uint b0 = (877940369);
            uint2 r0 = uint2(0, 1);
            TestUtils.AreEqual(a0 / b0, r0);

            uint2 a1 = uint2(1341281323, 2041215936);
            uint b1 = (1895153499);
            uint2 r1 = uint2(0, 1);
            TestUtils.AreEqual(a1 / b1, r1);

            uint2 a2 = uint2(1389479447, 1428493086);
            uint b2 = (1112377468);
            uint2 r2 = uint2(1, 1);
            TestUtils.AreEqual(a2 / b2, r2);

            uint2 a3 = uint2(1152385720, 1026467504);
            uint b3 = (1329193933);
            uint2 r3 = uint2(0, 0);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_div_scalar_wide()
        {
            uint a0 = (2021328826);
            uint2 b0 = uint2(874375696, 1507954497);
            uint2 r0 = uint2(2, 1);
            TestUtils.AreEqual(a0 / b0, r0);

            uint a1 = (2127317467);
            uint2 b1 = uint2(1203851704, 841281974);
            uint2 r1 = uint2(1, 2);
            TestUtils.AreEqual(a1 / b1, r1);

            uint a2 = (376202331);
            uint2 b2 = uint2(1544089754, 40402644);
            uint2 r2 = uint2(0, 9);
            TestUtils.AreEqual(a2 / b2, r2);

            uint a3 = (1986071898);
            uint2 b3 = uint2(2130326460, 1684745816);
            uint2 r3 = uint2(0, 1);
            TestUtils.AreEqual(a3 / b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mod_wide_wide()
        {
            uint2 a0 = uint2(1404166133, 2132673500);
            uint2 b0 = uint2(1451753818, 986752317);
            uint2 r0 = uint2(1404166133, 159168866);
            TestUtils.AreEqual(a0 % b0, r0);

            uint2 a1 = uint2(1226848706, 260867443);
            uint2 b1 = uint2(426407306, 388266591);
            uint2 r1 = uint2(374034094, 260867443);
            TestUtils.AreEqual(a1 % b1, r1);

            uint2 a2 = uint2(1657891933, 1665617201);
            uint2 b2 = uint2(1936904896, 1974281115);
            uint2 r2 = uint2(1657891933, 1665617201);
            TestUtils.AreEqual(a2 % b2, r2);

            uint2 a3 = uint2(1193460322, 939577022);
            uint2 b3 = uint2(2061811216, 1548000924);
            uint2 r3 = uint2(1193460322, 939577022);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mod_wide_scalar()
        {
            uint2 a0 = uint2(1161974084, 1730255826);
            uint b0 = (1619572929);
            uint2 r0 = uint2(1161974084, 110682897);
            TestUtils.AreEqual(a0 % b0, r0);

            uint2 a1 = uint2(1307617556, 108127332);
            uint b1 = (1348913399);
            uint2 r1 = uint2(1307617556, 108127332);
            TestUtils.AreEqual(a1 % b1, r1);

            uint2 a2 = uint2(158366308, 410222026);
            uint b2 = (608736703);
            uint2 r2 = uint2(158366308, 410222026);
            TestUtils.AreEqual(a2 % b2, r2);

            uint2 a3 = uint2(1124457489, 1777547989);
            uint b3 = (572642899);
            uint2 r3 = uint2(551814590, 59619292);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_mod_scalar_wide()
        {
            uint a0 = (732019691);
            uint2 b0 = uint2(1432618553, 1407625066);
            uint2 r0 = uint2(732019691, 732019691);
            TestUtils.AreEqual(a0 % b0, r0);

            uint a1 = (2104173412);
            uint2 b1 = uint2(787397289, 1250925010);
            uint2 r1 = uint2(529378834, 853248402);
            TestUtils.AreEqual(a1 % b1, r1);

            uint a2 = (1942782982);
            uint2 b2 = uint2(895419737, 1413458613);
            uint2 r2 = uint2(151943508, 529324369);
            TestUtils.AreEqual(a2 % b2, r2);

            uint a3 = (1057786657);
            uint2 b3 = uint2(895014416, 1411050342);
            uint2 r3 = uint2(162772241, 1057786657);
            TestUtils.AreEqual(a3 % b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_plus()
        {
            uint2 a0 = uint2(1389572610, 784638699);
            uint2 r0 = uint2(1389572610, 784638699);
            TestUtils.AreEqual(+a0, r0);

            uint2 a1 = uint2(1994582731, 1916426865);
            uint2 r1 = uint2(1994582731, 1916426865);
            TestUtils.AreEqual(+a1, r1);

            uint2 a2 = uint2(445404424, 2006066207);
            uint2 r2 = uint2(445404424, 2006066207);
            TestUtils.AreEqual(+a2, r2);

            uint2 a3 = uint2(790253154, 111908581);
            uint2 r3 = uint2(790253154, 111908581);
            TestUtils.AreEqual(+a3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_neg()
        {
            uint2 a0 = uint2(718733484, 283062622);
            uint2 r0 = uint2(3576233812, 4011904674);
            TestUtils.AreEqual(-a0, r0);

            uint2 a1 = uint2(1150527221, 2059224113);
            uint2 r1 = uint2(3144440075, 2235743183);
            TestUtils.AreEqual(-a1, r1);

            uint2 a2 = uint2(1889420629, 1443055648);
            uint2 r2 = uint2(2405546667, 2851911648);
            TestUtils.AreEqual(-a2, r2);

            uint2 a3 = uint2(2110619134, 946205741);
            uint2 r3 = uint2(2184348162, 3348761555);
            TestUtils.AreEqual(-a3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_prefix_inc()
        {
            uint2 a0 = uint2(1255324487, 1412620214);
            uint2 r0 = uint2(1255324488, 1412620215);
            TestUtils.AreEqual(++a0, r0);

            uint2 a1 = uint2(2004729755, 1001267099);
            uint2 r1 = uint2(2004729756, 1001267100);
            TestUtils.AreEqual(++a1, r1);

            uint2 a2 = uint2(300799799, 1377883623);
            uint2 r2 = uint2(300799800, 1377883624);
            TestUtils.AreEqual(++a2, r2);

            uint2 a3 = uint2(1403483584, 58299929);
            uint2 r3 = uint2(1403483585, 58299930);
            TestUtils.AreEqual(++a3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_postfix_inc()
        {
            uint2 a0 = uint2(482801952, 1525347232);
            uint2 r0 = uint2(482801952, 1525347232);
            TestUtils.AreEqual(a0++, r0);

            uint2 a1 = uint2(1327121509, 696835538);
            uint2 r1 = uint2(1327121509, 696835538);
            TestUtils.AreEqual(a1++, r1);

            uint2 a2 = uint2(1167198637, 1479259080);
            uint2 r2 = uint2(1167198637, 1479259080);
            TestUtils.AreEqual(a2++, r2);

            uint2 a3 = uint2(1764804294, 800117326);
            uint2 r3 = uint2(1764804294, 800117326);
            TestUtils.AreEqual(a3++, r3);
        }

        [TestCompiler]
        public static void uint2_operator_prefix_dec()
        {
            uint2 a0 = uint2(1786777392, 2114077793);
            uint2 r0 = uint2(1786777391, 2114077792);
            TestUtils.AreEqual(--a0, r0);

            uint2 a1 = uint2(1678527347, 332157813);
            uint2 r1 = uint2(1678527346, 332157812);
            TestUtils.AreEqual(--a1, r1);

            uint2 a2 = uint2(1908999543, 1105870615);
            uint2 r2 = uint2(1908999542, 1105870614);
            TestUtils.AreEqual(--a2, r2);

            uint2 a3 = uint2(1653790314, 432424960);
            uint2 r3 = uint2(1653790313, 432424959);
            TestUtils.AreEqual(--a3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_postfix_dec()
        {
            uint2 a0 = uint2(763128954, 1604006255);
            uint2 r0 = uint2(763128954, 1604006255);
            TestUtils.AreEqual(a0--, r0);

            uint2 a1 = uint2(851112563, 296277768);
            uint2 r1 = uint2(851112563, 296277768);
            TestUtils.AreEqual(a1--, r1);

            uint2 a2 = uint2(1793717563, 2018722301);
            uint2 r2 = uint2(1793717563, 2018722301);
            TestUtils.AreEqual(a2--, r2);

            uint2 a3 = uint2(1767809423, 1639458045);
            uint2 r3 = uint2(1767809423, 1639458045);
            TestUtils.AreEqual(a3--, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_and_wide_wide()
        {
            uint2 a0 = uint2(2092051178, 1746770686);
            uint2 b0 = uint2(272703892, 1322639335);
            uint2 r0 = uint2(268443776, 1209375462);
            TestUtils.AreEqual(a0 & b0, r0);

            uint2 a1 = uint2(1029274525, 1475004282);
            uint2 b1 = uint2(892833749, 1144239790);
            uint2 r1 = uint2(890309525, 1143113258);
            TestUtils.AreEqual(a1 & b1, r1);

            uint2 a2 = uint2(612016978, 797870200);
            uint2 b2 = uint2(1616750127, 886768760);
            uint2 r2 = uint2(542679554, 613023864);
            TestUtils.AreEqual(a2 & b2, r2);

            uint2 a3 = uint2(1438448989, 1307881465);
            uint2 b3 = uint2(151903875, 437958142);
            uint2 r3 = uint2(17619969, 135308792);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_and_wide_scalar()
        {
            uint2 a0 = uint2(1539818086, 1174036358);
            uint b0 = (1429236654);
            uint2 r0 = uint2(1358971430, 1160792966);
            TestUtils.AreEqual(a0 & b0, r0);

            uint2 a1 = uint2(829722249, 1883523687);
            uint b1 = (278534026);
            uint2 r1 = uint2(269485704, 268435970);
            TestUtils.AreEqual(a1 & b1, r1);

            uint2 a2 = uint2(972630451, 1980474728);
            uint b2 = (479408214);
            uint2 r2 = uint2(412164114, 335749184);
            TestUtils.AreEqual(a2 & b2, r2);

            uint2 a3 = uint2(1129809064, 182089936);
            uint b3 = (1581024627);
            uint2 r3 = uint2(1108640800, 169345104);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_and_scalar_wide()
        {
            uint a0 = (1464480071);
            uint2 b0 = uint2(880300166, 1801631129);
            uint2 r0 = uint2(340267014, 1128411393);
            TestUtils.AreEqual(a0 & b0, r0);

            uint a1 = (2146929359);
            uint2 b1 = uint2(134501242, 560052329);
            uint2 r1 = uint2(134480458, 560040009);
            TestUtils.AreEqual(a1 & b1, r1);

            uint a2 = (1883977874);
            uint2 b2 = uint2(1013494998, 1922782264);
            uint2 r2 = uint2(810037394, 1879773200);
            TestUtils.AreEqual(a2 & b2, r2);

            uint a3 = (691181116);
            uint2 b3 = uint2(462206052, 446227614);
            uint2 r3 = uint2(151032868, 135300124);
            TestUtils.AreEqual(a3 & b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_or_wide_wide()
        {
            uint2 a0 = uint2(734971681, 170686390);
            uint2 b0 = uint2(855541034, 1662326443);
            uint2 r0 = uint2(1006552875, 1799190463);
            TestUtils.AreEqual(a0 | b0, r0);

            uint2 a1 = uint2(1266964099, 1460491362);
            uint2 b1 = uint2(1355326851, 2034950208);
            uint2 r1 = uint2(1540159363, 2135946338);
            TestUtils.AreEqual(a1 | b1, r1);

            uint2 a2 = uint2(1803179461, 768462149);
            uint2 b2 = uint2(350174433, 267121140);
            uint2 r2 = uint2(2147450341, 804257269);
            TestUtils.AreEqual(a2 | b2, r2);

            uint2 a3 = uint2(987469872, 438875025);
            uint2 b3 = uint2(1311095923, 1505207657);
            uint2 r3 = uint2(2130689139, 1539291129);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_or_wide_scalar()
        {
            uint2 a0 = uint2(1734012999, 667885144);
            uint b0 = (724265524);
            uint2 r0 = uint2(1870396023, 804224636);
            TestUtils.AreEqual(a0 | b0, r0);

            uint2 a1 = uint2(1145828203, 548056872);
            uint b1 = (697078394);
            uint2 r1 = uint2(1842344827, 699318138);
            TestUtils.AreEqual(a1 | b1, r1);

            uint2 a2 = uint2(1693193261, 1923524974);
            uint b2 = (982993821);
            uint2 r2 = uint2(2130665405, 2058873855);
            TestUtils.AreEqual(a2 | b2, r2);

            uint2 a3 = uint2(1721498502, 1306607927);
            uint b3 = (629916984);
            uint2 r3 = uint2(1738276798, 1844167999);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_or_scalar_wide()
        {
            uint a0 = (1944842696);
            uint2 b0 = uint2(1797946902, 1995080562);
            uint2 r0 = uint2(2079064030, 2011952122);
            TestUtils.AreEqual(a0 | b0, r0);

            uint a1 = (1009785533);
            uint2 b1 = uint2(2078864395, 1738258290);
            uint2 r1 = uint2(2147024575, 2143010815);
            TestUtils.AreEqual(a1 | b1, r1);

            uint a2 = (2078839688);
            uint2 b2 = uint2(182771906, 331104563);
            uint2 r2 = uint2(2079126474, 2080166843);
            TestUtils.AreEqual(a2 | b2, r2);

            uint a3 = (1016101895);
            uint2 b3 = uint2(1555585463, 344959457);
            uint2 r3 = uint2(2092465591, 1017118183);
            TestUtils.AreEqual(a3 | b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_xor_wide_wide()
        {
            uint2 a0 = uint2(1451207246, 1326937873);
            uint2 b0 = uint2(973506398, 229917169);
            uint2 r0 = uint2(1819880720, 1117992672);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint2 a1 = uint2(1723637117, 1703580819);
            uint2 b1 = uint2(115811768, 824430321);
            uint2 r1 = uint2(1616623813, 1420384866);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint2 a2 = uint2(248456219, 102413373);
            uint2 b2 = uint2(1106935191, 1150807945);
            uint2 r2 = uint2(1328896396, 1116560308);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint2 a3 = uint2(1112748052, 786343099);
            uint2 b3 = uint2(1096766695, 405353279);
            uint2 r3 = uint2(51143923, 922195844);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_xor_wide_scalar()
        {
            uint2 a0 = uint2(1168710170, 1910166247);
            uint b0 = (1652551354);
            uint2 r0 = uint2(668398752, 329595997);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint2 a1 = uint2(770450475, 294543551);
            uint b1 = (137053244);
            uint2 r1 = uint2(633823255, 430253187);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint2 a2 = uint2(1408449906, 1927634471);
            uint b2 = (1818436467);
            uint2 r2 = uint2(1066409473, 512130388);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint2 a3 = uint2(1868775761, 2002455346);
            uint b3 = (2129912193);
            uint2 r3 = uint2(294691024, 162065075);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_xor_scalar_wide()
        {
            uint a0 = (1194539731);
            uint2 b0 = uint2(1838033352, 576935253);
            uint2 r0 = uint2(717034267, 1699770246);
            TestUtils.AreEqual(a0 ^ b0, r0);

            uint a1 = (399395950);
            uint2 b1 = uint2(250856040, 1425907707);
            uint2 r1 = uint2(423464454, 1127469973);
            TestUtils.AreEqual(a1 ^ b1, r1);

            uint a2 = (1076687299);
            uint2 b2 = uint2(983484392, 2124473834);
            uint2 r2 = uint2(2058499627, 1049367593);
            TestUtils.AreEqual(a2 ^ b2, r2);

            uint a3 = (2078261486);
            uint2 b3 = uint2(1921195479, 95097761);
            uint2 r3 = uint2(157080889, 2121585487);
            TestUtils.AreEqual(a3 ^ b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_left_shift()
        {
            uint2 a0 = uint2(931909748, 24051129);
            int b0 = (633406437);
            uint2 r0 = uint2(4051308160, 769636128);
            TestUtils.AreEqual(a0 << b0, r0);

            uint2 a1 = uint2(764104297, 915651018);
            int b1 = (615327136);
            uint2 r1 = uint2(764104297, 915651018);
            TestUtils.AreEqual(a1 << b1, r1);

            uint2 a2 = uint2(778230483, 1251270776);
            int b2 = (1053065817);
            uint2 r2 = uint2(2785017856, 4026531840);
            TestUtils.AreEqual(a2 << b2, r2);

            uint2 a3 = uint2(258942729, 1971396937);
            int b3 = (1285562176);
            uint2 r3 = uint2(258942729, 1971396937);
            TestUtils.AreEqual(a3 << b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_right_shift()
        {
            uint2 a0 = uint2(1366397886, 1724049991);
            int b0 = (1757774778);
            uint2 r0 = uint2(20, 25);
            TestUtils.AreEqual(a0 >> b0, r0);

            uint2 a1 = uint2(102473945, 1292455651);
            int b1 = (171782889);
            uint2 r1 = uint2(200144, 2524327);
            TestUtils.AreEqual(a1 >> b1, r1);

            uint2 a2 = uint2(86277781, 1261184742);
            int b2 = (56874046);
            uint2 r2 = uint2(0, 1);
            TestUtils.AreEqual(a2 >> b2, r2);

            uint2 a3 = uint2(1893257536, 1170864679);
            int b3 = (2046727266);
            uint2 r3 = uint2(473314384, 292716169);
            TestUtils.AreEqual(a3 >> b3, r3);
        }

        [TestCompiler]
        public static void uint2_operator_bitwise_not()
        {
            uint2 a0 = uint2(1581459784, 813914639);
            uint2 r0 = uint2(2713507511, 3481052656);
            TestUtils.AreEqual(~a0, r0);

            uint2 a1 = uint2(1110317406, 707106370);
            uint2 r1 = uint2(3184649889, 3587860925);
            TestUtils.AreEqual(~a1, r1);

            uint2 a2 = uint2(356629770, 678126530);
            uint2 r2 = uint2(3938337525, 3616840765);
            TestUtils.AreEqual(~a2, r2);

            uint2 a3 = uint2(1610491464, 476264684);
            uint2 r3 = uint2(2684475831, 3818702611);
            TestUtils.AreEqual(~a3, r3);
        }

        [TestCompiler]
        public static void uint2_shuffle_result_1()
        {
            uint2 a = uint2(0, 1);
            uint2 b = uint2(2, 3);

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX), (0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY), (1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX), (2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY), (3));
        }

        [TestCompiler]
        public static void uint2_shuffle_result_2()
        {
            uint2 a = uint2(0, 1);
            uint2 b = uint2(2, 3);

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftX), uint2(0, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftX), uint2(1, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX), uint2(2, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX), uint2(3, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY), uint2(0, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint2(1, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY), uint2(2, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY), uint2(3, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightX), uint2(0, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightX), uint2(1, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX), uint2(2, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX), uint2(3, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY), uint2(0, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightY), uint2(1, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightY), uint2(2, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY), uint2(3, 3));
        }

        [TestCompiler]
        public static void uint2_shuffle_result_3()
        {
            uint2 a = uint2(0, 1);
            uint2 b = uint2(2, 3);

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.RightY), uint3(2, 3, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightX), uint3(2, 0, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.RightY), uint3(3, 1, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint3(1, 1, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY), uint3(2, 1, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.RightY), uint3(0, 3, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY), uint3(2, 1, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.LeftX), uint3(3, 3, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY), uint3(2, 2, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftX), uint3(2, 2, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint3(0, 1, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightY), uint3(3, 2, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint3(0, 1, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightX), uint3(3, 2, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightY), uint3(0, 1, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint3(3, 1, 1));
        }

        [TestCompiler]
        public static void uint2_shuffle_result_4()
        {
            uint2 a = uint2(0, 1);
            uint2 b = uint2(2, 3);

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightX), uint4(0, 0, 1, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.LeftX, ShuffleComponent.RightY), uint4(2, 1, 0, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.RightX), uint4(3, 2, 3, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.RightY), uint4(2, 0, 3, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightX), uint4(0, 3, 0, 2));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftY), uint4(3, 0, 3, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.LeftX), uint4(2, 2, 3, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightY), uint4(2, 2, 0, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightX, ShuffleComponent.LeftY), uint4(0, 1, 2, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY, ShuffleComponent.RightY), uint4(2, 1, 3, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.LeftY), uint4(3, 3, 3, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), uint4(2, 2, 1, 1));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftX), uint4(3, 0, 0, 0));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY), uint4(2, 2, 2, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightY), uint4(0, 3, 0, 3));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftX), uint4(2, 0, 0, 0));
        }


    }
}
